// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/shenfay/go-ddd-scaffold/internal/infrastructure/persistence/model"
)

func newActivityLog(db *gorm.DB, opts ...gen.DOOption) activityLog {
	_activityLog := activityLog{}

	_activityLog.activityLogDo.UseDB(db, opts...)
	_activityLog.activityLogDo.UseModel(&model.ActivityLog{})

	tableName := _activityLog.activityLogDo.TableName()
	_activityLog.ALL = field.NewAsterisk(tableName)
	_activityLog.ID = field.NewInt64(tableName, "id")
	_activityLog.TenantID = field.NewInt64(tableName, "tenant_id")
	_activityLog.UserID = field.NewInt64(tableName, "user_id")
	_activityLog.Action = field.NewString(tableName, "action")
	_activityLog.Status = field.NewInt16(tableName, "status")
	_activityLog.IPAddress = field.NewString(tableName, "ip_address")
	_activityLog.UserAgent = field.NewString(tableName, "user_agent")
	_activityLog.Metadata = field.NewString(tableName, "metadata")
	_activityLog.OccurredAt = field.NewTime(tableName, "occurred_at")
	_activityLog.CreatedAt = field.NewTime(tableName, "created_at")

	_activityLog.fillFieldMap()

	return _activityLog
}

type activityLog struct {
	activityLogDo

	ALL        field.Asterisk
	ID         field.Int64  // Snowflake ID: 活动日志唯一标识
	TenantID   field.Int64  // 租户 ID: 操作所属的租户，NULL 表示系统级操作
	UserID     field.Int64  // 用户 ID: 执行操作的用户，关联 users 表
	Action     field.String // 操作类型：具体的活动名称，如 USER_LOGIN, USER_REGISTERED, USER_LOGOUT, ORDER_CREATED 等
	Status     field.Int16  // 操作状态：0-成功，1-失败，用于统计成功率
	IPAddress  field.String // IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6
	UserAgent  field.String // 用户代理：客户端的浏览器、移动设备或 API 客户端的完整信息
	Metadata   field.String // 扩展元数据：JSONB 格式存储操作的额外上下文，如登录方式、设备信息、地理位置等
	OccurredAt field.Time   // 发生时间：操作实际发生的时间戳
	CreatedAt  field.Time   // 创建时间：日志记录插入数据库的时间戳

	fieldMap map[string]field.Expr
}

func (a activityLog) Table(newTableName string) *activityLog {
	a.activityLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activityLog) As(alias string) *activityLog {
	a.activityLogDo.DO = *(a.activityLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activityLog) updateTableName(table string) *activityLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.TenantID = field.NewInt64(table, "tenant_id")
	a.UserID = field.NewInt64(table, "user_id")
	a.Action = field.NewString(table, "action")
	a.Status = field.NewInt16(table, "status")
	a.IPAddress = field.NewString(table, "ip_address")
	a.UserAgent = field.NewString(table, "user_agent")
	a.Metadata = field.NewString(table, "metadata")
	a.OccurredAt = field.NewTime(table, "occurred_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *activityLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activityLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["action"] = a.Action
	a.fieldMap["status"] = a.Status
	a.fieldMap["ip_address"] = a.IPAddress
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["metadata"] = a.Metadata
	a.fieldMap["occurred_at"] = a.OccurredAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a activityLog) clone(db *gorm.DB) activityLog {
	a.activityLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a activityLog) replaceDB(db *gorm.DB) activityLog {
	a.activityLogDo.ReplaceDB(db)
	return a
}

type activityLogDo struct{ gen.DO }

func (a activityLogDo) Debug() *activityLogDo {
	return a.withDO(a.DO.Debug())
}

func (a activityLogDo) WithContext(ctx context.Context) *activityLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activityLogDo) ReadDB() *activityLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a activityLogDo) WriteDB() *activityLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a activityLogDo) Session(config *gorm.Session) *activityLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a activityLogDo) Clauses(conds ...clause.Expression) *activityLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activityLogDo) Returning(value interface{}, columns ...string) *activityLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activityLogDo) Not(conds ...gen.Condition) *activityLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activityLogDo) Or(conds ...gen.Condition) *activityLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activityLogDo) Select(conds ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activityLogDo) Where(conds ...gen.Condition) *activityLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activityLogDo) Order(conds ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activityLogDo) Distinct(cols ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activityLogDo) Omit(cols ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activityLogDo) Join(table schema.Tabler, on ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activityLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activityLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activityLogDo) Group(cols ...field.Expr) *activityLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activityLogDo) Having(conds ...gen.Condition) *activityLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activityLogDo) Limit(limit int) *activityLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activityLogDo) Offset(offset int) *activityLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activityLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *activityLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activityLogDo) Unscoped() *activityLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activityLogDo) Create(values ...*model.ActivityLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activityLogDo) CreateInBatches(values []*model.ActivityLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activityLogDo) Save(values ...*model.ActivityLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activityLogDo) First() (*model.ActivityLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLog), nil
	}
}

func (a activityLogDo) Take() (*model.ActivityLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLog), nil
	}
}

func (a activityLogDo) Last() (*model.ActivityLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLog), nil
	}
}

func (a activityLogDo) Find() ([]*model.ActivityLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.ActivityLog), err
}

func (a activityLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ActivityLog, err error) {
	buf := make([]*model.ActivityLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activityLogDo) FindInBatches(result *[]*model.ActivityLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activityLogDo) Attrs(attrs ...field.AssignExpr) *activityLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activityLogDo) Assign(attrs ...field.AssignExpr) *activityLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activityLogDo) Joins(fields ...field.RelationField) *activityLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activityLogDo) Preload(fields ...field.RelationField) *activityLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activityLogDo) FirstOrInit() (*model.ActivityLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLog), nil
	}
}

func (a activityLogDo) FirstOrCreate() (*model.ActivityLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ActivityLog), nil
	}
}

func (a activityLogDo) FindByPage(offset int, limit int) (result []*model.ActivityLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activityLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activityLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activityLogDo) Delete(models ...*model.ActivityLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activityLogDo) withDO(do gen.Dao) *activityLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
