// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/shenfay/go-ddd-scaffold/internal/infrastructure/persistence/model"
)

func newAuditLog(db *gorm.DB, opts ...gen.DOOption) auditLog {
	_auditLog := auditLog{}

	_auditLog.auditLogDo.UseDB(db, opts...)
	_auditLog.auditLogDo.UseModel(&model.AuditLog{})

	tableName := _auditLog.auditLogDo.TableName()
	_auditLog.ALL = field.NewAsterisk(tableName)
	_auditLog.ID = field.NewInt64(tableName, "id")
	_auditLog.TenantID = field.NewInt64(tableName, "tenant_id")
	_auditLog.UserID = field.NewInt64(tableName, "user_id")
	_auditLog.Action = field.NewString(tableName, "action")
	_auditLog.ResourceType = field.NewString(tableName, "resource_type")
	_auditLog.ResourceID = field.NewInt64(tableName, "resource_id")
	_auditLog.RequestID = field.NewString(tableName, "request_id")
	_auditLog.IPAddress = field.NewString(tableName, "ip_address")
	_auditLog.UserAgent = field.NewString(tableName, "user_agent")
	_auditLog.Metadata = field.NewString(tableName, "metadata")
	_auditLog.Status = field.NewInt16(tableName, "status")
	_auditLog.ErrorMessage = field.NewString(tableName, "error_message")
	_auditLog.OccurredAt = field.NewTime(tableName, "occurred_at")
	_auditLog.CreatedAt = field.NewTime(tableName, "created_at")

	_auditLog.fillFieldMap()

	return _auditLog
}

type auditLog struct {
	auditLogDo

	ALL          field.Asterisk
	ID           field.Int64  // Snowflake ID: 审计日志唯一标识
	TenantID     field.Int64  // 租户 ID: 操作所属的租户，NULL 表示系统级操作（如管理员操作）
	UserID       field.Int64  // 用户 ID: 执行操作的用户，关联 users 表
	Action       field.String // 操作类型：具体的操作名称，如 CREATE_USER、UPDATE_TENANT_CONFIG、DELETE_ORDER 等
	ResourceType field.String // 资源类型：被操作的目标资源类型，如 User、Tenant、Order 等
	ResourceID   field.Int64  // 资源 ID: 被操作资源的具体 ID，用于定位具体记录
	RequestID    field.String // 请求 ID: 分布式链路追踪的唯一标识符，用于关联同一次请求的所有日志
	IPAddress    field.String // IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6
	UserAgent    field.String // 用户代理：客户端的浏览器、移动设备或 API 客户端的完整信息
	Metadata     field.String // 扩展元数据：JSONB 格式存储操作的额外上下文，如变更前后对比、操作参数等
	Status       field.Int16  // 操作状态：0-成功，1-失败，用于统计操作成功率
	ErrorMessage field.String // 错误信息：当操作失败时，记录详细的错误消息或堆栈跟踪
	OccurredAt   field.Time   // 发生时间：操作实际发生的时间戳，可能与 created_at 略有不同
	CreatedAt    field.Time   // 创建时间：日志记录插入数据库的时间戳

	fieldMap map[string]field.Expr
}

func (a auditLog) Table(newTableName string) *auditLog {
	a.auditLogDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a auditLog) As(alias string) *auditLog {
	a.auditLogDo.DO = *(a.auditLogDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *auditLog) updateTableName(table string) *auditLog {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.TenantID = field.NewInt64(table, "tenant_id")
	a.UserID = field.NewInt64(table, "user_id")
	a.Action = field.NewString(table, "action")
	a.ResourceType = field.NewString(table, "resource_type")
	a.ResourceID = field.NewInt64(table, "resource_id")
	a.RequestID = field.NewString(table, "request_id")
	a.IPAddress = field.NewString(table, "ip_address")
	a.UserAgent = field.NewString(table, "user_agent")
	a.Metadata = field.NewString(table, "metadata")
	a.Status = field.NewInt16(table, "status")
	a.ErrorMessage = field.NewString(table, "error_message")
	a.OccurredAt = field.NewTime(table, "occurred_at")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *auditLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *auditLog) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["id"] = a.ID
	a.fieldMap["tenant_id"] = a.TenantID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["action"] = a.Action
	a.fieldMap["resource_type"] = a.ResourceType
	a.fieldMap["resource_id"] = a.ResourceID
	a.fieldMap["request_id"] = a.RequestID
	a.fieldMap["ip_address"] = a.IPAddress
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["metadata"] = a.Metadata
	a.fieldMap["status"] = a.Status
	a.fieldMap["error_message"] = a.ErrorMessage
	a.fieldMap["occurred_at"] = a.OccurredAt
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a auditLog) clone(db *gorm.DB) auditLog {
	a.auditLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a auditLog) replaceDB(db *gorm.DB) auditLog {
	a.auditLogDo.ReplaceDB(db)
	return a
}

type auditLogDo struct{ gen.DO }

func (a auditLogDo) Debug() *auditLogDo {
	return a.withDO(a.DO.Debug())
}

func (a auditLogDo) WithContext(ctx context.Context) *auditLogDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a auditLogDo) ReadDB() *auditLogDo {
	return a.Clauses(dbresolver.Read)
}

func (a auditLogDo) WriteDB() *auditLogDo {
	return a.Clauses(dbresolver.Write)
}

func (a auditLogDo) Session(config *gorm.Session) *auditLogDo {
	return a.withDO(a.DO.Session(config))
}

func (a auditLogDo) Clauses(conds ...clause.Expression) *auditLogDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a auditLogDo) Returning(value interface{}, columns ...string) *auditLogDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a auditLogDo) Not(conds ...gen.Condition) *auditLogDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a auditLogDo) Or(conds ...gen.Condition) *auditLogDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a auditLogDo) Select(conds ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a auditLogDo) Where(conds ...gen.Condition) *auditLogDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a auditLogDo) Order(conds ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a auditLogDo) Distinct(cols ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a auditLogDo) Omit(cols ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a auditLogDo) Join(table schema.Tabler, on ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a auditLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a auditLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a auditLogDo) Group(cols ...field.Expr) *auditLogDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a auditLogDo) Having(conds ...gen.Condition) *auditLogDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a auditLogDo) Limit(limit int) *auditLogDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a auditLogDo) Offset(offset int) *auditLogDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a auditLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *auditLogDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a auditLogDo) Unscoped() *auditLogDo {
	return a.withDO(a.DO.Unscoped())
}

func (a auditLogDo) Create(values ...*model.AuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a auditLogDo) CreateInBatches(values []*model.AuditLog, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a auditLogDo) Save(values ...*model.AuditLog) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a auditLogDo) First() (*model.AuditLog, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Take() (*model.AuditLog, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Last() (*model.AuditLog, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) Find() ([]*model.AuditLog, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuditLog), err
}

func (a auditLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuditLog, err error) {
	buf := make([]*model.AuditLog, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a auditLogDo) FindInBatches(result *[]*model.AuditLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a auditLogDo) Attrs(attrs ...field.AssignExpr) *auditLogDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a auditLogDo) Assign(attrs ...field.AssignExpr) *auditLogDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a auditLogDo) Joins(fields ...field.RelationField) *auditLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a auditLogDo) Preload(fields ...field.RelationField) *auditLogDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a auditLogDo) FirstOrInit() (*model.AuditLog, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) FirstOrCreate() (*model.AuditLog, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditLog), nil
	}
}

func (a auditLogDo) FindByPage(offset int, limit int) (result []*model.AuditLog, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a auditLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a auditLogDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a auditLogDo) Delete(models ...*model.AuditLog) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *auditLogDo) withDO(do gen.Dao) *auditLogDo {
	a.DO = *do.(*gen.DO)
	return a
}
