// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/shenfay/go-ddd-scaffold/internal/infrastructure/persistence/model"
)

func newDomainEvent(db *gorm.DB, opts ...gen.DOOption) domainEvent {
	_domainEvent := domainEvent{}

	_domainEvent.domainEventDo.UseDB(db, opts...)
	_domainEvent.domainEventDo.UseModel(&model.DomainEvent{})

	tableName := _domainEvent.domainEventDo.TableName()
	_domainEvent.ALL = field.NewAsterisk(tableName)
	_domainEvent.ID = field.NewInt64(tableName, "id")
	_domainEvent.AggregateID = field.NewString(tableName, "aggregate_id")
	_domainEvent.AggregateType = field.NewString(tableName, "aggregate_type")
	_domainEvent.EventType = field.NewString(tableName, "event_type")
	_domainEvent.EventVersion = field.NewInt32(tableName, "event_version")
	_domainEvent.EventData = field.NewString(tableName, "event_data")
	_domainEvent.OccurredOn = field.NewTime(tableName, "occurred_on")
	_domainEvent.Metadata = field.NewString(tableName, "metadata")
	_domainEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_domainEvent.fillFieldMap()

	return _domainEvent
}

type domainEvent struct {
	domainEventDo

	ALL           field.Asterisk
	ID            field.Int64  // 自增 ID: 事件记录的唯一标识，使用 PostgreSQL 的 BIGSERIAL 类型
	AggregateID   field.String // 聚合根 ID: 触发事件的领域对象的唯一标识，如用户 ID、租户 ID 等
	AggregateType field.String // 聚合类型：触发事件的领域对象类型，如 User、Tenant、Order 等
	EventType     field.String // 事件类型：具体的事件名称，如 UserRegisteredEvent、UserLoggedInEvent 等
	EventVersion  field.Int32  // 事件版本：事件的版本号，用于乐观锁和事件升级管理
	EventData     field.String // 事件数据：JSONB 格式存储事件的完整数据，包含事件发生时所有的状态信息
	OccurredOn    field.Time   // 事件发生时间：领域事件在业务逻辑中实际发生的时间戳
	Metadata      field.String // 事件元数据：JSONB 格式存储事件的额外上下文，如 trace_id、user_id、correlation_id 等
	CreatedAt     field.Time   // 创建时间：事件记录插入数据库的时间戳

	fieldMap map[string]field.Expr
}

func (d domainEvent) Table(newTableName string) *domainEvent {
	d.domainEventDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d domainEvent) As(alias string) *domainEvent {
	d.domainEventDo.DO = *(d.domainEventDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *domainEvent) updateTableName(table string) *domainEvent {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.AggregateID = field.NewString(table, "aggregate_id")
	d.AggregateType = field.NewString(table, "aggregate_type")
	d.EventType = field.NewString(table, "event_type")
	d.EventVersion = field.NewInt32(table, "event_version")
	d.EventData = field.NewString(table, "event_data")
	d.OccurredOn = field.NewTime(table, "occurred_on")
	d.Metadata = field.NewString(table, "metadata")
	d.CreatedAt = field.NewTime(table, "created_at")

	d.fillFieldMap()

	return d
}

func (d *domainEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *domainEvent) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["aggregate_id"] = d.AggregateID
	d.fieldMap["aggregate_type"] = d.AggregateType
	d.fieldMap["event_type"] = d.EventType
	d.fieldMap["event_version"] = d.EventVersion
	d.fieldMap["event_data"] = d.EventData
	d.fieldMap["occurred_on"] = d.OccurredOn
	d.fieldMap["metadata"] = d.Metadata
	d.fieldMap["created_at"] = d.CreatedAt
}

func (d domainEvent) clone(db *gorm.DB) domainEvent {
	d.domainEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d domainEvent) replaceDB(db *gorm.DB) domainEvent {
	d.domainEventDo.ReplaceDB(db)
	return d
}

type domainEventDo struct{ gen.DO }

func (d domainEventDo) Debug() *domainEventDo {
	return d.withDO(d.DO.Debug())
}

func (d domainEventDo) WithContext(ctx context.Context) *domainEventDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d domainEventDo) ReadDB() *domainEventDo {
	return d.Clauses(dbresolver.Read)
}

func (d domainEventDo) WriteDB() *domainEventDo {
	return d.Clauses(dbresolver.Write)
}

func (d domainEventDo) Session(config *gorm.Session) *domainEventDo {
	return d.withDO(d.DO.Session(config))
}

func (d domainEventDo) Clauses(conds ...clause.Expression) *domainEventDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d domainEventDo) Returning(value interface{}, columns ...string) *domainEventDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d domainEventDo) Not(conds ...gen.Condition) *domainEventDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d domainEventDo) Or(conds ...gen.Condition) *domainEventDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d domainEventDo) Select(conds ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d domainEventDo) Where(conds ...gen.Condition) *domainEventDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d domainEventDo) Order(conds ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d domainEventDo) Distinct(cols ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d domainEventDo) Omit(cols ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d domainEventDo) Join(table schema.Tabler, on ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d domainEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d domainEventDo) RightJoin(table schema.Tabler, on ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d domainEventDo) Group(cols ...field.Expr) *domainEventDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d domainEventDo) Having(conds ...gen.Condition) *domainEventDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d domainEventDo) Limit(limit int) *domainEventDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d domainEventDo) Offset(offset int) *domainEventDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d domainEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *domainEventDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d domainEventDo) Unscoped() *domainEventDo {
	return d.withDO(d.DO.Unscoped())
}

func (d domainEventDo) Create(values ...*model.DomainEvent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d domainEventDo) CreateInBatches(values []*model.DomainEvent, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d domainEventDo) Save(values ...*model.DomainEvent) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d domainEventDo) First() (*model.DomainEvent, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainEvent), nil
	}
}

func (d domainEventDo) Take() (*model.DomainEvent, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainEvent), nil
	}
}

func (d domainEventDo) Last() (*model.DomainEvent, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainEvent), nil
	}
}

func (d domainEventDo) Find() ([]*model.DomainEvent, error) {
	result, err := d.DO.Find()
	return result.([]*model.DomainEvent), err
}

func (d domainEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DomainEvent, err error) {
	buf := make([]*model.DomainEvent, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d domainEventDo) FindInBatches(result *[]*model.DomainEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d domainEventDo) Attrs(attrs ...field.AssignExpr) *domainEventDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d domainEventDo) Assign(attrs ...field.AssignExpr) *domainEventDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d domainEventDo) Joins(fields ...field.RelationField) *domainEventDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d domainEventDo) Preload(fields ...field.RelationField) *domainEventDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d domainEventDo) FirstOrInit() (*model.DomainEvent, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainEvent), nil
	}
}

func (d domainEventDo) FirstOrCreate() (*model.DomainEvent, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DomainEvent), nil
	}
}

func (d domainEventDo) FindByPage(offset int, limit int) (result []*model.DomainEvent, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d domainEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d domainEventDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d domainEventDo) Delete(models ...*model.DomainEvent) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *domainEventDo) withDO(do gen.Dao) *domainEventDo {
	d.DO = *do.(*gen.DO)
	return d
}
