// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	ActivityLog    *activityLog
	DomainEvent    *domainEvent
	Outbox         *outbox
	Permission     *permission
	Role           *role
	RolePermission *rolePermission
	Tenant         *tenant
	TenantConfig   *tenantConfig
	TenantMember   *tenantMember
	User           *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ActivityLog = &Q.ActivityLog
	DomainEvent = &Q.DomainEvent
	Outbox = &Q.Outbox
	Permission = &Q.Permission
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	Tenant = &Q.Tenant
	TenantConfig = &Q.TenantConfig
	TenantMember = &Q.TenantMember
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		ActivityLog:    newActivityLog(db, opts...),
		DomainEvent:    newDomainEvent(db, opts...),
		Outbox:         newOutbox(db, opts...),
		Permission:     newPermission(db, opts...),
		Role:           newRole(db, opts...),
		RolePermission: newRolePermission(db, opts...),
		Tenant:         newTenant(db, opts...),
		TenantConfig:   newTenantConfig(db, opts...),
		TenantMember:   newTenantMember(db, opts...),
		User:           newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ActivityLog    activityLog
	DomainEvent    domainEvent
	Outbox         outbox
	Permission     permission
	Role           role
	RolePermission rolePermission
	Tenant         tenant
	TenantConfig   tenantConfig
	TenantMember   tenantMember
	User           user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ActivityLog:    q.ActivityLog.clone(db),
		DomainEvent:    q.DomainEvent.clone(db),
		Outbox:         q.Outbox.clone(db),
		Permission:     q.Permission.clone(db),
		Role:           q.Role.clone(db),
		RolePermission: q.RolePermission.clone(db),
		Tenant:         q.Tenant.clone(db),
		TenantConfig:   q.TenantConfig.clone(db),
		TenantMember:   q.TenantMember.clone(db),
		User:           q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ActivityLog:    q.ActivityLog.replaceDB(db),
		DomainEvent:    q.DomainEvent.replaceDB(db),
		Outbox:         q.Outbox.replaceDB(db),
		Permission:     q.Permission.replaceDB(db),
		Role:           q.Role.replaceDB(db),
		RolePermission: q.RolePermission.replaceDB(db),
		Tenant:         q.Tenant.replaceDB(db),
		TenantConfig:   q.TenantConfig.replaceDB(db),
		TenantMember:   q.TenantMember.replaceDB(db),
		User:           q.User.replaceDB(db),
	}
}

type queryCtx struct {
	ActivityLog    *activityLogDo
	DomainEvent    *domainEventDo
	Outbox         *outboxDo
	Permission     *permissionDo
	Role           *roleDo
	RolePermission *rolePermissionDo
	Tenant         *tenantDo
	TenantConfig   *tenantConfigDo
	TenantMember   *tenantMemberDo
	User           *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ActivityLog:    q.ActivityLog.WithContext(ctx),
		DomainEvent:    q.DomainEvent.WithContext(ctx),
		Outbox:         q.Outbox.WithContext(ctx),
		Permission:     q.Permission.WithContext(ctx),
		Role:           q.Role.WithContext(ctx),
		RolePermission: q.RolePermission.WithContext(ctx),
		Tenant:         q.Tenant.WithContext(ctx),
		TenantConfig:   q.TenantConfig.WithContext(ctx),
		TenantMember:   q.TenantMember.WithContext(ctx),
		User:           q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
