// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/shenfay/go-ddd-scaffold/internal/infrastructure/persistence/model"
)

func newOutbox(db *gorm.DB, opts ...gen.DOOption) outbox {
	_outbox := outbox{}

	_outbox.outboxDo.UseDB(db, opts...)
	_outbox.outboxDo.UseModel(&model.Outbox{})

	tableName := _outbox.outboxDo.TableName()
	_outbox.ALL = field.NewAsterisk(tableName)
	_outbox.ID = field.NewInt64(tableName, "id")
	_outbox.EventType = field.NewString(tableName, "event_type")
	_outbox.AggregateType = field.NewString(tableName, "aggregate_type")
	_outbox.AggregateID = field.NewString(tableName, "aggregate_id")
	_outbox.Payload = field.NewString(tableName, "payload")
	_outbox.Metadata = field.NewString(tableName, "metadata")
	_outbox.OccurredAt = field.NewTime(tableName, "occurred_at")
	_outbox.Processed = field.NewBool(tableName, "processed")
	_outbox.ProcessedAt = field.NewTime(tableName, "processed_at")
	_outbox.ErrorMessage = field.NewString(tableName, "error_message")
	_outbox.RetryCount = field.NewInt32(tableName, "retry_count")
	_outbox.CreatedAt = field.NewTime(tableName, "created_at")
	_outbox.UpdatedAt = field.NewTime(tableName, "updated_at")

	_outbox.fillFieldMap()

	return _outbox
}

type outbox struct {
	outboxDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键 ID: 自增主键
	EventType     field.String // 事件类型：如 user.registered, order.created 等
	AggregateType field.String // 聚合根类型：如 user, order 等
	AggregateID   field.String // 聚合根 ID: 关联的聚合根标识
	Payload       field.String // 事件载荷：序列化后的事件数据（JSONB 格式）
	Metadata      field.String // 元数据：事件的附加信息（可选）
	OccurredAt    field.Time   // 事件发生时间：领域事件实际发生的时间
	Processed     field.Bool   // 是否已处理：false-待处理，true-已发布到消息队列
	ProcessedAt   field.Time   // 处理时间：事件被发布到消息队列的时间
	ErrorMessage  field.String // 错误信息：最后一次处理失败的错误消息
	RetryCount    field.Int32  // 重试次数：事件处理失败的重试次数，最多 10 次
	CreatedAt     field.Time   // 创建时间：记录首次插入数据库的时间
	UpdatedAt     field.Time   // 更新时间：记录最后一次更新的时间，自动维护

	fieldMap map[string]field.Expr
}

func (o outbox) Table(newTableName string) *outbox {
	o.outboxDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o outbox) As(alias string) *outbox {
	o.outboxDo.DO = *(o.outboxDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *outbox) updateTableName(table string) *outbox {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.EventType = field.NewString(table, "event_type")
	o.AggregateType = field.NewString(table, "aggregate_type")
	o.AggregateID = field.NewString(table, "aggregate_id")
	o.Payload = field.NewString(table, "payload")
	o.Metadata = field.NewString(table, "metadata")
	o.OccurredAt = field.NewTime(table, "occurred_at")
	o.Processed = field.NewBool(table, "processed")
	o.ProcessedAt = field.NewTime(table, "processed_at")
	o.ErrorMessage = field.NewString(table, "error_message")
	o.RetryCount = field.NewInt32(table, "retry_count")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")

	o.fillFieldMap()

	return o
}

func (o *outbox) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *outbox) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 13)
	o.fieldMap["id"] = o.ID
	o.fieldMap["event_type"] = o.EventType
	o.fieldMap["aggregate_type"] = o.AggregateType
	o.fieldMap["aggregate_id"] = o.AggregateID
	o.fieldMap["payload"] = o.Payload
	o.fieldMap["metadata"] = o.Metadata
	o.fieldMap["occurred_at"] = o.OccurredAt
	o.fieldMap["processed"] = o.Processed
	o.fieldMap["processed_at"] = o.ProcessedAt
	o.fieldMap["error_message"] = o.ErrorMessage
	o.fieldMap["retry_count"] = o.RetryCount
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
}

func (o outbox) clone(db *gorm.DB) outbox {
	o.outboxDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o outbox) replaceDB(db *gorm.DB) outbox {
	o.outboxDo.ReplaceDB(db)
	return o
}

type outboxDo struct{ gen.DO }

func (o outboxDo) Debug() *outboxDo {
	return o.withDO(o.DO.Debug())
}

func (o outboxDo) WithContext(ctx context.Context) *outboxDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o outboxDo) ReadDB() *outboxDo {
	return o.Clauses(dbresolver.Read)
}

func (o outboxDo) WriteDB() *outboxDo {
	return o.Clauses(dbresolver.Write)
}

func (o outboxDo) Session(config *gorm.Session) *outboxDo {
	return o.withDO(o.DO.Session(config))
}

func (o outboxDo) Clauses(conds ...clause.Expression) *outboxDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o outboxDo) Returning(value interface{}, columns ...string) *outboxDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o outboxDo) Not(conds ...gen.Condition) *outboxDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o outboxDo) Or(conds ...gen.Condition) *outboxDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o outboxDo) Select(conds ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o outboxDo) Where(conds ...gen.Condition) *outboxDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o outboxDo) Order(conds ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o outboxDo) Distinct(cols ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o outboxDo) Omit(cols ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o outboxDo) Join(table schema.Tabler, on ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o outboxDo) LeftJoin(table schema.Tabler, on ...field.Expr) *outboxDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o outboxDo) RightJoin(table schema.Tabler, on ...field.Expr) *outboxDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o outboxDo) Group(cols ...field.Expr) *outboxDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o outboxDo) Having(conds ...gen.Condition) *outboxDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o outboxDo) Limit(limit int) *outboxDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o outboxDo) Offset(offset int) *outboxDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o outboxDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *outboxDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o outboxDo) Unscoped() *outboxDo {
	return o.withDO(o.DO.Unscoped())
}

func (o outboxDo) Create(values ...*model.Outbox) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o outboxDo) CreateInBatches(values []*model.Outbox, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o outboxDo) Save(values ...*model.Outbox) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o outboxDo) First() (*model.Outbox, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Outbox), nil
	}
}

func (o outboxDo) Take() (*model.Outbox, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Outbox), nil
	}
}

func (o outboxDo) Last() (*model.Outbox, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Outbox), nil
	}
}

func (o outboxDo) Find() ([]*model.Outbox, error) {
	result, err := o.DO.Find()
	return result.([]*model.Outbox), err
}

func (o outboxDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Outbox, err error) {
	buf := make([]*model.Outbox, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o outboxDo) FindInBatches(result *[]*model.Outbox, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o outboxDo) Attrs(attrs ...field.AssignExpr) *outboxDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o outboxDo) Assign(attrs ...field.AssignExpr) *outboxDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o outboxDo) Joins(fields ...field.RelationField) *outboxDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o outboxDo) Preload(fields ...field.RelationField) *outboxDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o outboxDo) FirstOrInit() (*model.Outbox, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Outbox), nil
	}
}

func (o outboxDo) FirstOrCreate() (*model.Outbox, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Outbox), nil
	}
}

func (o outboxDo) FindByPage(offset int, limit int) (result []*model.Outbox, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o outboxDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o outboxDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o outboxDo) Delete(models ...*model.Outbox) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *outboxDo) withDO(do gen.Dao) *outboxDo {
	o.DO = *do.(*gen.DO)
	return o
}
