// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/shenfay/go-ddd-scaffold/internal/infrastructure/persistence/model"
)

func newTenantConfig(db *gorm.DB, opts ...gen.DOOption) tenantConfig {
	_tenantConfig := tenantConfig{}

	_tenantConfig.tenantConfigDo.UseDB(db, opts...)
	_tenantConfig.tenantConfigDo.UseModel(&model.TenantConfig{})

	tableName := _tenantConfig.tenantConfigDo.TableName()
	_tenantConfig.ALL = field.NewAsterisk(tableName)
	_tenantConfig.TenantID = field.NewInt64(tableName, "tenant_id")
	_tenantConfig.MaxMembers = field.NewInt32(tableName, "max_members")
	_tenantConfig.StorageLimit = field.NewInt64(tableName, "storage_limit")
	_tenantConfig.FeatureFlags = field.NewString(tableName, "feature_flags")
	_tenantConfig.Branding = field.NewString(tableName, "branding")
	_tenantConfig.CustomSettings = field.NewString(tableName, "custom_settings")
	_tenantConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_tenantConfig.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tenantConfig.fillFieldMap()

	return _tenantConfig
}

type tenantConfig struct {
	tenantConfigDo

	ALL            field.Asterisk
	TenantID       field.Int64  // 租户 ID: 与 tenants 表一对一关联，作为主键同时是外键，级联删除
	MaxMembers     field.Int32  // 最大成员数：租户允许添加的用户数量上限，受订阅计划限制
	StorageLimit   field.Int64  // 存储限制（字节）：租户可使用的总存储空间，默认 10GB(10737418240 字节)
	FeatureFlags   field.String // 功能开关：JSONB 格式存储各功能的启用状态，如 {"dark_mode": true, "advanced_analytics": false}
	Branding       field.String // 品牌配置：JSONB 格式存储白标定制信息，如 logo URL、主题色、自定义域名等
	CustomSettings field.String // 自定义配置：JSONB 格式存储租户特定的业务配置项，如审批流程、通知模板等
	CreatedAt      field.Time   // 创建时间：租户配置首次创建的时间戳
	UpdatedAt      field.Time   // 更新时间：租户配置最后一次更新的时间戳，自动维护

	fieldMap map[string]field.Expr
}

func (t tenantConfig) Table(newTableName string) *tenantConfig {
	t.tenantConfigDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenantConfig) As(alias string) *tenantConfig {
	t.tenantConfigDo.DO = *(t.tenantConfigDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenantConfig) updateTableName(table string) *tenantConfig {
	t.ALL = field.NewAsterisk(table)
	t.TenantID = field.NewInt64(table, "tenant_id")
	t.MaxMembers = field.NewInt32(table, "max_members")
	t.StorageLimit = field.NewInt64(table, "storage_limit")
	t.FeatureFlags = field.NewString(table, "feature_flags")
	t.Branding = field.NewString(table, "branding")
	t.CustomSettings = field.NewString(table, "custom_settings")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tenantConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenantConfig) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["max_members"] = t.MaxMembers
	t.fieldMap["storage_limit"] = t.StorageLimit
	t.fieldMap["feature_flags"] = t.FeatureFlags
	t.fieldMap["branding"] = t.Branding
	t.fieldMap["custom_settings"] = t.CustomSettings
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tenantConfig) clone(db *gorm.DB) tenantConfig {
	t.tenantConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenantConfig) replaceDB(db *gorm.DB) tenantConfig {
	t.tenantConfigDo.ReplaceDB(db)
	return t
}

type tenantConfigDo struct{ gen.DO }

func (t tenantConfigDo) Debug() *tenantConfigDo {
	return t.withDO(t.DO.Debug())
}

func (t tenantConfigDo) WithContext(ctx context.Context) *tenantConfigDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenantConfigDo) ReadDB() *tenantConfigDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenantConfigDo) WriteDB() *tenantConfigDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenantConfigDo) Session(config *gorm.Session) *tenantConfigDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenantConfigDo) Clauses(conds ...clause.Expression) *tenantConfigDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenantConfigDo) Returning(value interface{}, columns ...string) *tenantConfigDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenantConfigDo) Not(conds ...gen.Condition) *tenantConfigDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenantConfigDo) Or(conds ...gen.Condition) *tenantConfigDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenantConfigDo) Select(conds ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenantConfigDo) Where(conds ...gen.Condition) *tenantConfigDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenantConfigDo) Order(conds ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenantConfigDo) Distinct(cols ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenantConfigDo) Omit(cols ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenantConfigDo) Join(table schema.Tabler, on ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenantConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenantConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenantConfigDo) Group(cols ...field.Expr) *tenantConfigDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenantConfigDo) Having(conds ...gen.Condition) *tenantConfigDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenantConfigDo) Limit(limit int) *tenantConfigDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenantConfigDo) Offset(offset int) *tenantConfigDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenantConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenantConfigDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenantConfigDo) Unscoped() *tenantConfigDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenantConfigDo) Create(values ...*model.TenantConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenantConfigDo) CreateInBatches(values []*model.TenantConfig, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenantConfigDo) Save(values ...*model.TenantConfig) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenantConfigDo) First() (*model.TenantConfig, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantConfig), nil
	}
}

func (t tenantConfigDo) Take() (*model.TenantConfig, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantConfig), nil
	}
}

func (t tenantConfigDo) Last() (*model.TenantConfig, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantConfig), nil
	}
}

func (t tenantConfigDo) Find() ([]*model.TenantConfig, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenantConfig), err
}

func (t tenantConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantConfig, err error) {
	buf := make([]*model.TenantConfig, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenantConfigDo) FindInBatches(result *[]*model.TenantConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenantConfigDo) Attrs(attrs ...field.AssignExpr) *tenantConfigDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenantConfigDo) Assign(attrs ...field.AssignExpr) *tenantConfigDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenantConfigDo) Joins(fields ...field.RelationField) *tenantConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenantConfigDo) Preload(fields ...field.RelationField) *tenantConfigDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenantConfigDo) FirstOrInit() (*model.TenantConfig, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantConfig), nil
	}
}

func (t tenantConfigDo) FirstOrCreate() (*model.TenantConfig, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantConfig), nil
	}
}

func (t tenantConfigDo) FindByPage(offset int, limit int) (result []*model.TenantConfig, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenantConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenantConfigDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenantConfigDo) Delete(models ...*model.TenantConfig) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenantConfigDo) withDO(do gen.Dao) *tenantConfigDo {
	t.DO = *do.(*gen.DO)
	return t
}
