#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DDD Modeling Assistant - DDD 建模助手
辅助领域建模和聚合根设计
"""

import os
import sys
from pathlib import Path


class ColorLogger:
    """彩色日志输出"""
    
    BLUE = '\033[0;34m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    NC = '\033[0m'
    
    @classmethod
    def info(cls, msg):
        print(f"{cls.BLUE}[INFO]{cls.NC} {msg}")
    
    @classmethod
    def success(cls, msg):
        print(f"{cls.GREEN}[SUCCESS]{cls.NC} {msg}")
    
    @classmethod
    def warning(cls, msg):
        print(f"{cls.YELLOW}[WARNING]{cls.NC} {msg}")
    
    @classmethod
    def error(cls, msg):
        print(f"{cls.RED}[ERROR]{cls.NC} {msg}")


def get_project_root():
    """动态获取项目根目录"""
    script_dir = Path(__file__).parent
    return (script_dir / '../../../..').resolve()


def create_aggregate_root(name, domain='', output_dir=None, project_root=None):
    """创建聚合根模板"""
    if project_root is None:
        project_root = get_project_root()
    
    if output_dir is None:
        output_dir = project_root / "backend" / "internal" / "domain" / domain / "entity" if domain else \
                    project_root / "backend" / "internal" / "domain" / name.lower() / "entity"
    
    ColorLogger.info(f"创建聚合根：{name}")
    
    # 创建目录
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 生成聚合根代码
    aggregate_code = f'''// Code generated by ddd-modeling-assistant. DO NOT EDIT.
// source: {name}

package entity

import (
\t"time"
\t"your-project/internal/domain/shared/event"
)

// {name} 聚合根
type {name} struct {{
\t// 聚合根 ID
\tID string
	
\t// 创建时间
\tCreatedAt time.Time
	
\t// 更新时间
\tUpdatedAt time.Time
	
\t// 领域事件
\tevents []event.DomainEvent
	
\t// TODO: 添加聚合根的字段
}}

// New{name} 创建新的聚合根
func New{name}() *{name} {{
\treturn &{name}{{
\t\tCreatedAt: time.Now(),
\t\tUpdatedAt: time.Now(),
\t\tevents:    make([]event.DomainEvent, 0),
\t}}
}}

// RegisterEvent 注册领域事件
func (a *{name}) RegisterEvent(evt event.DomainEvent) {{
\ta.events = append(a.events, evt)
}}

// PullEvents 拉取并清除所有事件
func (a *{name}) PullEvents() []event.DomainEvent {{
\tevents := a.events
\ta.events = nil
\treturn events
}}

// HasUncommittedEvents 是否有未提交的事件
func (a *{name}) HasUncommittedEvents() bool {{
\treturn len(a.events) > 0
}}
'''
    
    filename = f"{name.lower()}.go"
    with open(output_dir / filename, 'w', encoding='utf-8') as f:
        f.write(aggregate_code)
    
    ColorLogger.success(f"生成聚合根：{filename}")
    
    # 同时生成 Repository 接口
    repo_code = f'''// Code generated by ddd-modeling-assistant. DO NOT EDIT.
// {name} Repository 接口

package repository

import (
\t"context"
\t"your-project/internal/domain/{domain or name.lower()}/entity"
)

// {name}Repository {name} 仓储接口
type {name}Repository interface {{
\t// Store 保存聚合根
\tStore(ctx context.Context, agg *entity.{name}) error
\t
\t// FindByID 根据 ID 查找
\tFindByID(ctx context.Context, id string) (*entity.{name}, error)
\t
\t// FindAll 查找所有
\tFindAll(ctx context.Context, offset, limit int) ([]*entity.{name}, int64, error)
\t
\t// Delete 删除
\tDelete(ctx context.Context, id string) error
}}
'''
    
    repo_dir = output_dir.parent / "repository"
    repo_dir.mkdir(parents=True, exist_ok=True)
    
    with open(repo_dir / f"{name.lower()}_repository.go", 'w', encoding='utf-8') as f:
        f.write(repo_code)
    
    ColorLogger.success(f"生成 Repository 接口：{name.lower()}_repository.go")
    
    return True


def create_value_object(name, output_dir=None, project_root=None):
    """创建值对象模板"""
    if project_root is None:
        project_root = get_project_root()
    
    if output_dir is None:
        output_dir = project_root / "backend" / "internal" / "domain" / "shared" / "valueobject"
    
    ColorLogger.info(f"创建值对象：{name}")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    vo_code = f'''// Code generated by ddd-modeling-assistant. DO NOT EDIT.
// source: {name}

package valueobject

import (
\t"errors"
)

// {name} 值对象
type {name} struct {{
\t// TODO: 添加值对象的字段
\tvalue string
}}

// New{name} 创建值对象
func New{name}(value string) (*{name}, error) {{
\tvo := &{name}{{
\t\tvalue: value,
\t}}
\t
\t// 验证逻辑
\tif err := vo.validate(); err != nil {{
\t\treturn nil, err
\t}}
\t
\treturn vo, nil
}}

// validate 验证
func (vo *{name}) validate() error {{
\tif vo.value == "" {{
\t\treturn errors.New("value cannot be empty")
\t}}
\treturn nil
}}

// Value 获取值
func (vo *{name}) Value() string {{
\treturn vo.value
}}

// Equal 判断是否相等
func (vo *{name}) Equal(other *{name}) bool {{
\tif other == nil {{
\t\treturn false
\t}}
\treturn vo.value == other.value
}}
'''
    
    filename = f"{name.lower()}.go"
    with open(output_dir / filename, 'w', encoding='utf-8') as f:
        f.write(vo_code)
    
    ColorLogger.success(f"生成值对象：{filename}")
    return True


def create_domain_event(name, output_dir=None, project_root=None):
    """创建领域事件模板"""
    if project_root is None:
        project_root = get_project_root()
    
    if output_dir is None:
        output_dir = project_root / "backend" / "internal" / "domain" / "shared" / "event"
    
    ColorLogger.info(f"创建领域事件：{name}")
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 注意：Go 代码中的花括号需要双写以转义
    event_code = '''// Code generated by ddd-modeling-assistant. DO NOT EDIT.
// source: {name}

package event

import (
\t"time"
)

// {name} 领域事件
type {name} struct {{
\t// 事件 ID
\tID string
	
\t// 事件类型
\tType string
	
\t// 发生时间
\tOccurredAt time.Time
	
\t// 数据负载
\tPayload map[string]interface{{}}
}}

// New{name} 创建领域事件
func New{name}(payload map[string]interface{{}}) *{name} {{
\treturn &{name}{{
\t\tID:         generateID(), // TODO: 实现 ID 生成
\t\tType:       "{name}",
\t\tOccurredAt: time.Now(),
\t\tPayload:    payload,
\t}}
}}

// GetID 获取事件 ID
func (e *{name}) GetID() string {{
\treturn e.ID
}}

// GetType 获取事件类型
func (e *{name}) GetType() string {{
\treturn e.Type
}}

// GetOccurredAt 获取发生时间
func (e *{name}) GetOccurredAt() time.Time {{
\treturn e.OccurredAt
}}

// GetPayload 获取数据负载
func (e *{name}) GetPayload() map[string]interface{{}} {{
\treturn e.Payload
}}
'''.replace('{name}', name)
    
    filename = f"{name.lower()}.go"
    with open(output_dir / filename, 'w', encoding='utf-8') as f:
        f.write(event_code)
    
    ColorLogger.success(f"生成领域事件：{filename}")
    return True


def list_domain_objects(project_root=None):
    """列出领域对象"""
    if project_root is None:
        project_root = get_project_root()
    
    domain_dir = project_root / "backend" / "internal" / "domain"
    
    if not domain_dir.exists():
        ColorLogger.error("领域目录不存在")
        return
    
    ColorLogger.info("已定义的领域:")
    
    domains = [d for d in domain_dir.iterdir() if d.is_dir()]
    for domain in domains:
        print(f"  - {domain.name}")


def main():
    """主函数"""
    import argparse
    
    parser = argparse.ArgumentParser(description='DDD 建模助手')
    parser.add_argument('--action', type=str, default='create',
                       choices=['create', 'list'],
                       help='操作类型')
    parser.add_argument('--type', type=str, default='aggregate',
                       choices=['aggregate', 'value-object', 'event'],
                       help='对象类型')
    parser.add_argument('--name', type=str, required=True,
                       help='对象名称')
    parser.add_argument('--domain', type=str, default='',
                       help='领域名称')
    parser.add_argument('--output', type=str, default='',
                       help='输出目录')
    
    args = parser.parse_args()
    
    project_root = get_project_root()
    output_dir = Path(args.output) if args.output else None
    
    if args.action == 'create':
        if args.type == 'aggregate':
            create_aggregate_root(args.name, args.domain, output_dir, project_root)
        elif args.type == 'value-object':
            create_value_object(args.name, output_dir, project_root)
        elif args.type == 'event':
            create_domain_event(args.name, output_dir, project_root)
        
        ColorLogger.success("DDD 建模完成!")
        
    elif args.action == 'list':
        list_domain_objects(project_root)


if __name__ == '__main__':
    main()
