// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivityLog = "activity_logs"

// ActivityLog mapped from table <activity_logs>
type ActivityLog struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID: 活动日志唯一标识" json:"id"`                                                                                                                                                                      // Snowflake ID: 活动日志唯一标识
	TenantID   *int64     `gorm:"column:tenant_id;type:bigint;index:idx_activity_logs_tenant_id,priority:1;comment:租户 ID: 操作所属的租户，NULL 表示系统级操作" json:"tenant_id"`                                                                                                                 // 租户 ID: 操作所属的租户，NULL 表示系统级操作
	UserID     int64      `gorm:"column:user_id;type:bigint;not null;index:idx_activity_logs_user_id,priority:1;comment:用户 ID: 执行操作的用户，关联 users 表" json:"user_id"`                                                                                                                // 用户 ID: 执行操作的用户，关联 users 表
	Action     string     `gorm:"column:action;type:character varying(100);not null;index:idx_activity_logs_action,priority:1;comment:操作类型：具体的活动名称，如 USER_LOGIN, USER_REGISTERED, USER_LOGOUT, ORDER_CREATED 等" json:"action"`                                                    // 操作类型：具体的活动名称，如 USER_LOGIN, USER_REGISTERED, USER_LOGOUT, ORDER_CREATED 等
	Status     *int16     `gorm:"column:status;type:smallint;index:idx_activity_logs_status,priority:1;index:idx_activity_logs_failed,priority:1;comment:操作状态：0-成功，1-失败，用于统计成功率" json:"status"`                                                                                   // 操作状态：0-成功，1-失败，用于统计成功率
	IPAddress  *string    `gorm:"column:ip_address;type:inet;comment:IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6" json:"ip_address"`                                                                                                                                                 // IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6
	UserAgent  *string    `gorm:"column:user_agent;type:text;comment:用户代理：客户端的浏览器、移动设备或 API 客户端的完整信息" json:"user_agent"`                                                                                                                                                          // 用户代理：客户端的浏览器、移动设备或 API 客户端的完整信息
	Metadata   *string    `gorm:"column:metadata;type:jsonb;index:idx_activity_logs_metadata,priority:1;default:{};comment:扩展元数据：JSONB 格式存储操作的额外上下文，如登录方式、设备信息、地理位置等" json:"metadata"`                                                                                            // 扩展元数据：JSONB 格式存储操作的额外上下文，如登录方式、设备信息、地理位置等
	OccurredAt time.Time  `gorm:"column:occurred_at;type:timestamp without time zone;not null;index:idx_activity_logs_occurred_at,priority:1;index:idx_activity_logs_user_id,priority:2;index:idx_activity_logs_tenant_id,priority:2;comment:发生时间：操作实际发生的时间戳" json:"occurred_at"` // 发生时间：操作实际发生的时间戳
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：日志记录插入数据库的时间戳" json:"created_at"`                                                                                                                      // 创建时间：日志记录插入数据库的时间戳
}

// TableName ActivityLog's table name
func (*ActivityLog) TableName() string {
	return TableNameActivityLog
}
