// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomainEvent = "domain_events"

// DomainEvent mapped from table <domain_events>
type DomainEvent struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID：事件唯一标识，使用雪花算法生成" json:"id"`                                                                                      // Snowflake ID：事件唯一标识，使用雪花算法生成
	AggregateID   string     `gorm:"column:aggregate_id;type:character varying(100);not null;index:idx_domain_events_aggregate,priority:1;comment:聚合根 ID: 关联的聚合根标识" json:"aggregate_id"`                   // 聚合根 ID: 关联的聚合根标识
	AggregateType string     `gorm:"column:aggregate_type;type:character varying(50);not null;index:idx_domain_events_aggregate,priority:2;comment:聚合根类型：如 user, order 等" json:"aggregate_type"`           // 聚合根类型：如 user, order 等
	EventType     string     `gorm:"column:event_type;type:character varying(100);not null;index:idx_domain_events_type,priority:1;comment:事件类型：如 user.registered, order.created 等" json:"event_type"`     // 事件类型：如 user.registered, order.created 等
	EventData     string     `gorm:"column:event_data;type:jsonb;not null;comment:事件数据：序列化后的事件数据（JSONB 格式）" json:"event_data"`                                                                             // 事件数据：序列化后的事件数据（JSONB 格式）
	Metadata      *string    `gorm:"column:metadata;type:jsonb;comment:元数据：事件的附加信息（可选）" json:"metadata"`                                                                                                   // 元数据：事件的附加信息（可选）
	OccurredAt    *time.Time `gorm:"column:occurred_at;type:timestamp without time zone;not null;index:idx_domain_events_occurred,priority:1;default:now();comment:事件发生时间：领域事件实际发生的时间" json:"occurred_at"` // 事件发生时间：领域事件实际发生的时间
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:now();comment:创建时间：记录插入数据库的时间" json:"created_at"`                                                  // 创建时间：记录插入数据库的时间
}

// TableName DomainEvent's table name
func (*DomainEvent) TableName() string {
	return TableNameDomainEvent
}
