// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomainEvent = "domain_events"

// DomainEvent mapped from table <domain_events>
type DomainEvent struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:自增 ID: 事件记录的唯一标识，使用 PostgreSQL 的 BIGSERIAL 类型" json:"id"`                                                             // 自增 ID: 事件记录的唯一标识，使用 PostgreSQL 的 BIGSERIAL 类型
	AggregateID   string     `gorm:"column:aggregate_id;type:character varying(100);not null;index:idx_domain_events_aggregate,priority:1;comment:聚合根 ID: 触发事件的领域对象的唯一标识，如用户 ID、租户 ID 等" json:"aggregate_id"`         // 聚合根 ID: 触发事件的领域对象的唯一标识，如用户 ID、租户 ID 等
	AggregateType string     `gorm:"column:aggregate_type;type:character varying(100);not null;index:idx_domain_events_aggregate,priority:2;comment:聚合类型：触发事件的领域对象类型，如 User、Tenant、Order 等" json:"aggregate_type"`    // 聚合类型：触发事件的领域对象类型，如 User、Tenant、Order 等
	EventType     string     `gorm:"column:event_type;type:character varying(100);not null;index:idx_domain_events_type,priority:1;comment:事件类型：具体的事件名称，如 UserRegisteredEvent、UserLoggedInEvent 等" json:"event_type"` // 事件类型：具体的事件名称，如 UserRegisteredEvent、UserLoggedInEvent 等
	EventVersion  int32      `gorm:"column:event_version;type:integer;not null;comment:事件版本：事件的版本号，用于乐观锁和事件升级管理" json:"event_version"`                                                                                // 事件版本：事件的版本号，用于乐观锁和事件升级管理
	EventData     string     `gorm:"column:event_data;type:jsonb;not null;comment:事件数据：JSONB 格式存储事件的完整数据，包含事件发生时所有的状态信息" json:"event_data"`                                                                           // 事件数据：JSONB 格式存储事件的完整数据，包含事件发生时所有的状态信息
	OccurredOn    time.Time  `gorm:"column:occurred_on;type:timestamp without time zone;not null;index:idx_domain_events_occurred,priority:1;comment:事件发生时间：领域事件在业务逻辑中实际发生的时间戳" json:"occurred_on"`                   // 事件发生时间：领域事件在业务逻辑中实际发生的时间戳
	Processed     *bool      `gorm:"column:processed;type:boolean;index:idx_domain_events_processed,priority:1;comment:是否已处理：标记事件是否已被事件处理器或消息队列消费者处理" json:"processed"`                                               // 是否已处理：标记事件是否已被事件处理器或消息队列消费者处理
	Metadata      *string    `gorm:"column:metadata;type:jsonb;index:idx_domain_events_metadata,priority:1;default:{};comment:事件元数据：JSONB 格式存储事件的额外上下文，如 trace_id、user_id、correlation_id 等" json:"metadata"`          // 事件元数据：JSONB 格式存储事件的额外上下文，如 trace_id、user_id、correlation_id 等
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：事件记录插入数据库的时间戳" json:"created_at"`                                                       // 创建时间：事件记录插入数据库的时间戳
}

// TableName DomainEvent's table name
func (*DomainEvent) TableName() string {
	return TableNameDomainEvent
}
