// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLoginLog = "login_logs"

// LoginLog mapped from table <login_logs>
type LoginLog struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID: 登录日志唯一标识" json:"id"`                                                                                                                                                               // Snowflake ID: 登录日志唯一标识
	UserID        int64      `gorm:"column:user_id;type:bigint;not null;index:idx_login_logs_user_id,priority:1;comment:用户 ID: 尝试登录的用户，关联 users 表" json:"user_id"`                                                                                                            // 用户 ID: 尝试登录的用户，关联 users 表
	TenantID      *int64     `gorm:"column:tenant_id;type:bigint;index:idx_login_logs_tenant_id,priority:1;comment:租户 ID: 用户登录到的具体租户，NULL 表示全局登录或未选择租户" json:"tenant_id"`                                                                                                     // 租户 ID: 用户登录到的具体租户，NULL 表示全局登录或未选择租户
	LoginType     *string    `gorm:"column:login_type;type:character varying(50);default:password;comment:登录方式：password(密码登录)/sso(单点登录)/oauth(第三方授权)/magic_link(魔术链接免密登录)" json:"login_type"`                                                                                 // 登录方式：password(密码登录)/sso(单点登录)/oauth(第三方授权)/magic_link(魔术链接免密登录)
	LoginStatus   string     `gorm:"column:login_status;type:character varying(50);not null;index:idx_login_logs_status,priority:1;comment:登录状态：success(成功)/failed(失败)/blocked(被阻止)" json:"login_status"`                                                                     // 登录状态：success(成功)/failed(失败)/blocked(被阻止)
	IPAddress     string     `gorm:"column:ip_address;type:inet;not null;index:idx_login_logs_ip_address,priority:1;comment:IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6" json:"ip_address"`                                                                                      // IP 地址：客户端的网络 IP 地址，INET 类型支持 IPv4 和 IPv6
	UserAgent     *string    `gorm:"column:user_agent;type:text;comment:用户代理：客户端的完整 User-Agent 字符串，包含浏览器、设备等信息" json:"user_agent"`                                                                                                                                            // 用户代理：客户端的完整 User-Agent 字符串，包含浏览器、设备等信息
	DeviceType    *string    `gorm:"column:device_type;type:character varying(50);comment:设备类型：desktop(桌面端)/mobile(移动端)/tablet(平板)" json:"device_type"`                                                                                                                       // 设备类型：desktop(桌面端)/mobile(移动端)/tablet(平板)
	OsInfo        *string    `gorm:"column:os_info;type:character varying(100);comment:操作系统信息：如 Windows 11、macOS 13.2、iOS 16.3、Android 13 等" json:"os_info"`                                                                                                                  // 操作系统信息：如 Windows 11、macOS 13.2、iOS 16.3、Android 13 等
	BrowserInfo   *string    `gorm:"column:browser_info;type:character varying(100);comment:浏览器信息：如 Chrome 120.0、Safari 17.0、Firefox 121.0 等" json:"browser_info"`                                                                                                            // 浏览器信息：如 Chrome 120.0、Safari 17.0、Firefox 121.0 等
	Country       *string    `gorm:"column:country;type:character varying(50);comment:国家：基于 IP 地址解析的地理位置" json:"country"`                                                                                                                                                     // 国家：基于 IP 地址解析的地理位置，如"中国"、"美国"等
	City          *string    `gorm:"column:city;type:character varying(100);comment:城市：基于 IP 地址解析的地理位置" json:"city"`                                                                                                                                                          // 城市：基于 IP 地址解析的地理位置，如"北京"、"上海"等
	FailureReason *string    `gorm:"column:failure_reason;type:character varying(200);comment:失败原因：登录失败时的具体原因描述" json:"failure_reason"`                                                                                                                                       // 失败原因：登录失败时的具体原因描述，如"密码错误"、"账户已锁定"等
	IsSuspicious  *bool      `gorm:"column:is_suspicious;type:boolean;index:idx_login_logs_suspicious,priority:1;comment:是否可疑：标记异常的登录行为，如异地登录、频繁失败等" json:"is_suspicious"`                                                                                                    // 是否可疑：标记异常的登录行为，如异地登录、频繁失败等
	RiskScore     *int32     `gorm:"column:risk_score;type:integer;comment:风险评分：0-100 分，综合评估本次登录的风险程度，分数越高风险越大" json:"risk_score"`                                                                                                                                            // 风险评分：0-100 分，综合评估本次登录的风险程度，分数越高风险越大
	SessionID     *string    `gorm:"column:session_id;type:character varying(100);comment:会话 ID: 登录成功后生成的会话标识符，用于后续请求的身份验证" json:"session_id"`                                                                                                                                // 会话 ID: 登录成功后生成的会话标识符，用于后续请求的身份验证
	AccessTokenID *string    `gorm:"column:access_token_id;type:character varying(100);comment:访问令牌 ID: JWT Token 的唯一标识符，用于 Token 管理和撤销" json:"access_token_id"`                                                                                                              // 访问令牌 ID: JWT Token 的唯一标识符，用于 Token 管理和撤销
	OccurredAt    time.Time  `gorm:"column:occurred_at;type:timestamp without time zone;not null;index:idx_login_logs_occurred_at,priority:1;index:idx_login_logs_user_id,priority:2;index:idx_login_logs_tenant_id,priority:2;comment:发生时间：登录尝试实际发生的时间戳" json:"occurred_at"` // 发生时间：登录尝试实际发生的时间戳
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：日志记录插入数据库的时间戳" json:"created_at"`                                                                                                               // 创建时间：日志记录插入数据库的时间戳
}

// TableName LoginLog's table name
func (*LoginLog) TableName() string {
	return TableNameLoginLog
}
