// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOutbox = "outbox"

// Outbox mapped from table <outbox>
type Outbox struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;comment:主键 ID: 自增主键" json:"id"`                                                                                                   // 主键 ID: 自增主键
	EventType     string     `gorm:"column:event_type;type:character varying(100);not null;index:idx_outbox_type,priority:1;comment:事件类型：如 user.registered, order.created 等" json:"event_type"`        // 事件类型：如 user.registered, order.created 等
	AggregateType string     `gorm:"column:aggregate_type;type:character varying(50);not null;index:idx_outbox_aggregate,priority:1;comment:聚合根类型：如 user, order 等" json:"aggregate_type"`              // 聚合根类型：如 user, order 等
	AggregateID   string     `gorm:"column:aggregate_id;type:character varying(100);not null;index:idx_outbox_aggregate,priority:2;comment:聚合根 ID: 关联的聚合根标识" json:"aggregate_id"`                      // 聚合根 ID: 关联的聚合根标识
	Payload       string     `gorm:"column:payload;type:jsonb;not null;comment:事件载荷：序列化后的事件数据（JSONB 格式）" json:"payload"`                                                                               // 事件载荷：序列化后的事件数据（JSONB 格式）
	Metadata      *string    `gorm:"column:metadata;type:jsonb;comment:元数据：事件的附加信息（可选）" json:"metadata"`                                                                                               // 元数据：事件的附加信息（可选）
	OccurredAt    *time.Time `gorm:"column:occurred_at;type:timestamp without time zone;not null;index:idx_outbox_unprocessed,priority:1;default:now();comment:事件发生时间：领域事件实际发生的时间" json:"occurred_at"` // 事件发生时间：领域事件实际发生的时间
	Processed     bool       `gorm:"column:processed;type:boolean;not null;comment:是否已处理：false-待处理，true-已发布到消息队列" json:"processed"`                                                                    // 是否已处理：false-待处理，true-已发布到消息队列
	ProcessedAt   *time.Time `gorm:"column:processed_at;type:timestamp without time zone;comment:处理时间：事件被发布到消息队列的时间" json:"processed_at"`                                                              // 处理时间：事件被发布到消息队列的时间
	ErrorMessage  *string    `gorm:"column:error_message;type:text;comment:错误信息：最后一次处理失败的错误消息" json:"error_message"`                                                                                   // 错误信息：最后一次处理失败的错误消息
	RetryCount    int32      `gorm:"column:retry_count;type:integer;not null;index:idx_outbox_retry,priority:1;comment:重试次数：事件处理失败的重试次数，最多 10 次" json:"retry_count"`                                   // 重试次数：事件处理失败的重试次数，最多 10 次
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp without time zone;not null;default:now();comment:创建时间：记录首次插入数据库的时间" json:"created_at"`                                            // 创建时间：记录首次插入数据库的时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp without time zone;not null;default:now();comment:更新时间：记录最后一次更新的时间，自动维护" json:"updated_at"`                                        // 更新时间：记录最后一次更新的时间，自动维护
}

// TableName Outbox's table name
func (*Outbox) TableName() string {
	return TableNameOutbox
}
