// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permissions"

// Permission mapped from table <permissions>
type Permission struct {
	ID              int64            `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID: 权限唯一标识，使用雪花算法生成" json:"id"`                                                                                           // Snowflake ID: 权限唯一标识，使用雪花算法生成
	Name            string           `gorm:"column:name;type:character varying(100);not null;comment:权限名称：权限的显示名称，如"创建用户"、"查看账单"等" json:"name"`                                                                          // 权限名称：权限的显示名称，如"创建用户"、"查看账单"等
	Code            string           `gorm:"column:code;type:character varying(100);not null;index:idx_permissions_code,priority:1;comment:权限编码：全局唯一的权限标识符，用于代码中判断权限，如"user:create"" json:"code"`                        // 权限编码：全局唯一的权限标识符，用于代码中判断权限，如"user:create"
	Resource        string           `gorm:"column:resource;type:character varying(100);not null;index:idx_permissions_resource_action,priority:1;comment:资源类型：权限作用的目标资源，如 user/tenant/billing/order 等" json:"resource"` // 资源类型：权限作用的目标资源，如 user/tenant/billing/order 等
	Action          string           `gorm:"column:action;type:character varying(50);not null;index:idx_permissions_resource_action,priority:2;comment:操作类型：对资源的操作，如 create/read/update/delete，*表示所有操作" json:"action"`   // 操作类型：对资源的操作，如 create/read/update/delete，*表示所有操作
	Scope           *string          `gorm:"column:scope;type:character varying(50);index:idx_permissions_scope,priority:1;default:tenant;comment:作用域：system-系统级权限（仅管理员可用），tenant-租户级权限（普通用户可用）" json:"scope"`           // 作用域：system-系统级权限（仅管理员可用），tenant-租户级权限（普通用户可用）
	Description     *string          `gorm:"column:description;type:text;comment:权限描述：权限的详细介绍或使用场景说明" json:"description"`                                                                                                // 权限描述：权限的详细介绍或使用场景说明
	Metadata        *string          `gorm:"column:metadata;type:jsonb;index:idx_permissions_metadata,priority:1;default:{};comment:扩展元数据：JSONB 格式存储权限的额外配置或约束条件" json:"metadata"`                                       // 扩展元数据：JSONB 格式存储权限的额外配置或约束条件
	CreatedAt       *time.Time       `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：权限首次创建的时间戳" json:"created_at"`                                                     // 创建时间：权限首次创建的时间戳
	UpdatedAt       *time.Time       `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:更新时间：权限记录最后一次更新的时间戳，自动维护" json:"updated_at"`                                            // 更新时间：权限记录最后一次更新的时间戳，自动维护
	RolePermissions []RolePermission `gorm:"foreignKey:PermissionID" json:"role_permissions"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
