// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID              int64            `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID: 角色唯一标识，使用雪花算法生成" json:"id"`                                                                                                                                                                     // Snowflake ID: 角色唯一标识，使用雪花算法生成
	TenantID        *int64           `gorm:"column:tenant_id;type:bigint;uniqueIndex:idx_roles_tenant_code_unique,priority:1;index:idx_roles_code,priority:1;index:idx_roles_tenant_id,priority:1;comment:租户 ID: NULL 表示系统预定义角色（全局可用），有值表示租户自定义角色（仅该租户可用）" json:"tenant_id"`                       // 租户 ID: NULL 表示系统预定义角色（全局可用），有值表示租户自定义角色（仅该租户可用）
	Name            string           `gorm:"column:name;type:character varying(50);not null;comment:角色名称：角色的显示名称，如"管理员"、"普通成员"等" json:"name"`                                                                                                                                                      // 角色名称：角色的显示名称，如"管理员"、"普通成员"等
	Code            string           `gorm:"column:code;type:character varying(50);not null;uniqueIndex:idx_roles_system_code_unique,priority:1;uniqueIndex:idx_roles_tenant_code_unique,priority:2;index:idx_roles_code,priority:2;comment:角色编码：角色的唯一标识符，如"admin"、"member"等，同一租户下唯一" json:"code"` // 角色编码：角色的唯一标识符，如"admin"、"member"等，同一租户下唯一
	Description     *string          `gorm:"column:description;type:text;comment:角色描述：角色的详细介绍或职责说明" json:"description"`                                                                                                                                                                            // 角色描述：角色的详细介绍或职责说明
	IsSystem        *bool            `gorm:"column:is_system;type:boolean;index:idx_roles_is_system,priority:1;comment:是否系统角色：TRUE=系统预定义角色（tenant_id 必须为 NULL），FALSE=租户自定义角色（tenant_id 必须有值）" json:"is_system"`                                                                                    // 是否系统角色：TRUE=系统预定义角色（tenant_id 必须为 NULL），FALSE=租户自定义角色（tenant_id 必须有值）
	Permissions     *string          `gorm:"column:permissions;type:jsonb;index:idx_roles_permissions,priority:1;default:[];comment:权限列表：JSONB 数组格式存储权限码，如 ["user:create", "user:read"]" json:"permissions"`                                                                                       // 权限列表：JSONB 数组格式存储权限码，如 ["user:create", "user:read"]
	Version         *int32           `gorm:"column:version;type:integer;comment:乐观锁版本号：用于并发更新控制，每次更新递增" json:"version"`                                                                                                                                                                            // 乐观锁版本号：用于并发更新控制，每次更新递增
	DeletedAt       gorm.DeletedAt   `gorm:"column:deleted_at;type:timestamp without time zone;index:idx_roles_deleted_at,priority:1;comment:软删除时间：标记删除的时间戳，NULL 表示未删除" json:"deleted_at"`                                                                                                         // 软删除时间：标记删除的时间戳，NULL 表示未删除
	CreatedAt       *time.Time       `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：角色首次创建的时间戳" json:"created_at"`                                                                                                                               // 创建时间：角色首次创建的时间戳
	UpdatedAt       *time.Time       `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:更新时间：角色记录最后一次更新的时间戳，自动维护" json:"updated_at"`                                                                                                                      // 更新时间：角色记录最后一次更新的时间戳，自动维护
	RolePermissions []RolePermission `gorm:"foreignKey:RoleID" json:"role_permissions"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
