// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRolePermission = "role_permissions"

// RolePermission mapped from table <role_permissions>
type RolePermission struct {
	RoleID       int64      `gorm:"column:role_id;type:bigint;primaryKey;index:idx_role_permissions_role_id,priority:1;comment:角色 ID: 关联 roles 表，标识具体的角色" json:"role_id"`                          // 角色 ID: 关联 roles 表，标识具体的角色
	PermissionID int64      `gorm:"column:permission_id;type:bigint;primaryKey;index:idx_role_permissions_permission_id,priority:1;comment:权限 ID: 关联 permissions 表，标识具体的权限项" json:"permission_id"` // 权限 ID: 关联 permissions 表，标识具体的权限项
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：角色被授予该权限的时间戳" json:"created_at"`                                      // 创建时间：角色被授予该权限的时间戳
	Role         Role       `gorm:"foreignKey:RoleID" json:"role"`
	Permission   Permission `gorm:"foreignKey:PermissionID" json:"permission"`
}

// TableName RolePermission's table name
func (*RolePermission) TableName() string {
	return TableNameRolePermission
}
