// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenantConfig = "tenant_configs"

// TenantConfig mapped from table <tenant_configs>
type TenantConfig struct {
	TenantID       int64      `gorm:"column:tenant_id;type:bigint;primaryKey;comment:租户 ID: 与 tenants 表一对一关联，作为主键同时是外键，级联删除" json:"tenant_id"`                                                                                              // 租户 ID: 与 tenants 表一对一关联，作为主键同时是外键，级联删除
	MaxMembers     *int32     `gorm:"column:max_members;type:integer;default:100;comment:最大成员数：租户允许添加的用户数量上限，受订阅计划限制" json:"max_members"`                                                                                                   // 最大成员数：租户允许添加的用户数量上限，受订阅计划限制
	StorageLimit   *int64     `gorm:"column:storage_limit;type:bigint;default:10737418240;comment:存储限制（字节）：租户可使用的总存储空间，默认 10GB(10737418240 字节)" json:"storage_limit"`                                                                       // 存储限制（字节）：租户可使用的总存储空间，默认 10GB(10737418240 字节)
	FeatureFlags   *string    `gorm:"column:feature_flags;type:jsonb;index:idx_tenant_configs_feature_flags,priority:1;default:{};comment:功能开关：JSONB 格式存储各功能的启用状态，如 {"dark_mode": true, "advanced_analytics": false}" json:"feature_flags"` // 功能开关：JSONB 格式存储各功能的启用状态，如 {"dark_mode": true, "advanced_analytics": false}
	Branding       *string    `gorm:"column:branding;type:jsonb;index:idx_tenant_configs_branding,priority:1;default:{};comment:品牌配置：JSONB 格式存储白标定制信息，如 logo URL、主题色、自定义域名等" json:"branding"`                                               // 品牌配置：JSONB 格式存储白标定制信息，如 logo URL、主题色、自定义域名等
	CustomSettings *string    `gorm:"column:custom_settings;type:jsonb;index:idx_tenant_configs_custom_settings,priority:1;default:{};comment:自定义配置：JSONB 格式存储租户特定的业务配置项，如审批流程、通知模板等" json:"custom_settings"`                               // 自定义配置：JSONB 格式存储租户特定的业务配置项，如审批流程、通知模板等
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：租户配置首次创建的时间戳" json:"created_at"`                                                                             // 创建时间：租户配置首次创建的时间戳
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:更新时间：租户配置最后一次更新的时间戳，自动维护" json:"updated_at"`                                                                      // 更新时间：租户配置最后一次更新的时间戳，自动维护
}

// TableName TenantConfig's table name
func (*TenantConfig) TableName() string {
	return TableNameTenantConfig
}
