// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTenantMember = "tenant_members"

// TenantMember mapped from table <tenant_members>
type TenantMember struct {
	TenantID  int64          `gorm:"column:tenant_id;type:bigint;primaryKey;index:idx_tenant_members_tenant_id_status,priority:1;comment:租户 ID: 关联 tenants 表，标识成员所属的租户" json:"tenant_id"`   // 租户 ID: 关联 tenants 表，标识成员所属的租户
	UserID    int64          `gorm:"column:user_id;type:bigint;primaryKey;index:idx_tenant_members_user_id,priority:1;comment:用户 ID: 关联 users 表，标识具体的成员用户" json:"user_id"`                  // 用户 ID: 关联 users 表，标识具体的成员用户
	RoleID    *int64         `gorm:"column:role_id;type:bigint;index:idx_tenant_members_role_id,priority:1;comment:角色 ID: 关联 roles 表，定义用户在租户中的权限等级" json:"role_id"`                         // 角色 ID: 关联 roles 表，定义用户在租户中的权限等级
	JoinedAt  *time.Time     `gorm:"column:joined_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:加入时间：用户正式加入租户的时间戳" json:"joined_at"`                                // 加入时间：用户正式加入租户的时间戳
	InvitedBy *int64         `gorm:"column:invited_by;type:bigint;comment:邀请人 ID: 发起邀请的用户 ID，关联 users 表" json:"invited_by"`                                                                 // 邀请人 ID: 发起邀请的用户 ID，关联 users 表
	Status    int16          `gorm:"column:status;type:smallint;not null;index:idx_tenant_members_tenant_id_status,priority:2;comment:成员状态：0-待邀请，1-活跃，2-已移除，3-已拒绝" json:"status"`           // 成员状态：0-待邀请，1-活跃，2-已移除，3-已拒绝
	Metadata  *string        `gorm:"column:metadata;type:jsonb;index:idx_tenant_members_metadata,priority:1;default:{};comment:扩展信息：JSONB 格式存储部门、职位、入职日期等自定义字段" json:"metadata"`            // 扩展信息：JSONB 格式存储部门、职位、入职日期等自定义字段
	CreatedAt *time.Time     `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:创建时间：记录首次创建的时间戳" json:"created_at"`                                // 创建时间：记录首次创建的时间戳
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:更新时间：记录最后一次更新的时间戳，自动维护" json:"updated_at"`                         // 更新时间：记录最后一次更新的时间戳，自动维护
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone;index:idx_tenant_members_deleted_at,priority:1;comment:软删除时间：标记删除的时间戳，NULL 表示未删除" json:"deleted_at"` // 软删除时间：标记删除的时间戳，NULL 表示未删除
	Tenant    Tenant         `gorm:"foreignKey:TenantID" json:"tenant"`
	User      User           `gorm:"foreignKey:UserID" json:"user"`
	Role      Role           `gorm:"foreignKey:RoleID" json:"role"`
}

// TableName TenantMember's table name
func (*TenantMember) TableName() string {
	return TableNameTenantMember
}
