// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                int64          `gorm:"column:id;type:bigint;primaryKey;comment:Snowflake ID: 用户唯一标识，使用雪花算法生成" json:"id"`                                                                                                          // Snowflake ID: 用户唯一标识，使用雪花算法生成
	Username          string         `gorm:"column:username;type:character varying(50);not null;index:idx_users_username,priority:1;comment:用户名：用户登录名，全局唯一，长度 3-50 字符" json:"username"`                                                 // 用户名：用户登录名，全局唯一，长度 3-50 字符
	Email             string         `gorm:"column:email;type:character varying(255);not null;index:idx_users_email,priority:1;comment:邮箱：用户邮箱地址，用于登录和接收通知，全局唯一" json:"email"`                                                          // 邮箱：用户邮箱地址，用于登录和接收通知，全局唯一
	PasswordHash      string         `gorm:"column:password_hash;type:character varying(255);not null;comment:密码哈希：使用 bcrypt 算法加密后的密码" json:"password_hash"`                                                                            // 密码哈希：使用 bcrypt 算法加密后的密码
	Status            int16          `gorm:"column:status;type:smallint;not null;index:idx_users_status_deleted_at,priority:1;index:idx_users_status,priority:1;comment:用户状态：0-待激活，1-激活，2-禁用，3-锁定" json:"status"`                       // 用户状态：0-待激活，1-激活，2-禁用，3-锁定
	DisplayName       *string        `gorm:"column:display_name;type:character varying(100);comment:显示名称：用户对外显示的名称，可为空" json:"display_name"`                                                                                            // 显示名称：用户对外显示的名称，可为空
	Gender            *int16         `gorm:"column:gender;type:smallint;comment:性别：0-未知，1-男，2-女，3-其他" json:"gender"`                                                                                                                    // 性别：0-未知，1-男，2-女，3-其他
	PhoneNumber       *string        `gorm:"column:phone_number;type:character varying(20);comment:电话号码：用户手机号码，用于短信验证等" json:"phone_number"`                                                                                            // 电话号码：用户手机号码，用于短信验证等
	AvatarURL         *string        `gorm:"column:avatar_url;type:character varying(500);comment:头像 URL: 用户头像图片的存储地址" json:"avatar_url"`                                                                                               // 头像 URL: 用户头像图片的存储地址
	LastLoginAt       *time.Time     `gorm:"column:last_login_at;type:timestamp without time zone;comment:最后登录时间：用户最后一次成功登录的时间戳" json:"last_login_at"`                                                                                  // 最后登录时间：用户最后一次成功登录的时间戳
	LoginCount        *int32         `gorm:"column:login_count;type:integer;comment:登录次数：用户累计成功登录的次数" json:"login_count"`                                                                                                               // 登录次数：用户累计成功登录的次数
	FailedAttempts    *int32         `gorm:"column:failed_attempts;type:integer;comment:连续失败登录次数：用于账户安全锁定策略" json:"failed_attempts"`                                                                                                    // 连续失败登录次数：用于账户安全锁定策略
	LockedUntil       *time.Time     `gorm:"column:locked_until;type:timestamp without time zone;comment:账户锁定截止时间：临时锁定的结束时间，永久锁定为 NULL" json:"locked_until"`                                                                            // 账户锁定截止时间：临时锁定的结束时间，永久锁定为 NULL
	Version           *int32         `gorm:"column:version;type:integer;comment:乐观锁版本号：用于并发更新控制，每次更新递增" json:"version"`                                                                                                                 // 乐观锁版本号：用于并发更新控制，每次更新递增
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp without time zone;index:idx_users_status_deleted_at,priority:2;index:idx_users_deleted_at,priority:1;comment:软删除时间：标记删除的时间戳，NULL 表示未删除" json:"deleted_at"` // 软删除时间：标记删除的时间戳，NULL 表示未删除
	CreatedAt         *time.Time     `gorm:"column:created_at;type:timestamp without time zone;index:idx_users_created_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间：记录首次创建的时间戳" json:"created_at"`                              // 创建时间：记录首次创建的时间戳
	UpdatedAt         *time.Time     `gorm:"column:updated_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP;comment:更新时间：记录最后一次更新的时间戳，自动维护" json:"updated_at"`                                                             // 更新时间：记录最后一次更新的时间戳，自动维护
	TenantMemberships []TenantMember `gorm:"foreignKey:UserID" json:"tenant_memberships"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
