app:
  name: "MathFun-Backend"
  port: 8080
  env: "development"

database:
  host: "localhost"
  port: 5432
  user: "mathfun"
  password: "math111"
  dbname: "mathfun"
  sslmode: "disable"

jwt:
  secret_key: "your-secret-key-change-in-production"
  expire_in: 24h

log:
  level: "info"

