// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "使用用户名或邮箱和密码进行登录，获取访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录凭证",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.AuthenticateCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功返回令牌和用户信息",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.AuthenticateResult"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "401": {
                        "description": "认证失败",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "使当前访问令牌失效",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户登出",
                "responses": {
                    "204": {
                        "description": "登出成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取当前登录用户的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "获取当前用户",
                "responses": {
                    "200": {
                        "description": "当前用户信息",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.UserInfoResult"
                        }
                    },
                    "401": {
                        "description": "未授权",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "使用刷新令牌获取新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "刷新访问令牌",
                "parameters": [
                    {
                        "description": "刷新令牌",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.RefreshTokenCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功返回新令牌",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.RefreshTokenResult"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "401": {
                        "description": "令牌无效",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "创建新用户账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.RegisterCommand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "注册成功返回用户信息",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_auth.RegisterResult"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "409": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "根据用户 ID 获取用户详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户详情",
                        "schema": {}
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定用户的详细信息（部分更新）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_user_usecase.UpdateProfileCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}/password": {
            "put": {
                "description": "修改指定用户的登录密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改用户密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "原密码和新密码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_application_user_usecase.ChangePasswordCommand"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "修改成功",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.AuthenticateCommand": {
            "type": "object",
            "properties": {
                "identifier": {
                    "description": "用户名或邮箱",
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.AuthenticateResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expires_in": {
                    "description": "过期时间（秒）",
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.RefreshTokenCommand": {
            "type": "object",
            "properties": {
                "current_token": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.RefreshTokenResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.RegisterCommand": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.RegisterResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_auth.UserInfoResult": {
            "type": "object",
            "properties": {
                "display_name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_user_usecase.ChangePasswordCommand": {
            "type": "object",
            "properties": {
                "ipaddress": {
                    "type": "string"
                },
                "newPassword": {
                    "type": "string"
                },
                "oldPassword": {
                    "type": "string"
                },
                "userID": {
                    "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_domain_user_valueobject.UserID"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_application_user_usecase.UpdateProfileCommand": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "gender": {
                    "description": "指针类型支持可选参数",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_domain_user_valueobject.UserGender"
                        }
                    ]
                },
                "lastName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "userID": {
                    "$ref": "#/definitions/github_com_shenfay_go-ddd-scaffold_internal_domain_user_valueobject.UserID"
                }
            }
        },
        "github_com_shenfay_go-ddd-scaffold_internal_domain_user_valueobject.UserGender": {
            "type": "integer",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "UserGenderUnknown",
                "UserGenderMale",
                "UserGenderFemale",
                "UserGenderOther"
            ]
        },
        "github_com_shenfay_go-ddd-scaffold_internal_domain_user_valueobject.UserID": {
            "type": "object"
        },
        "github_com_shenfay_go-ddd-scaffold_internal_interfaces_http_handler.APIResponse": {
            "description": "API 统一响应格式（用于 Swagger 文档）",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "在 Header 中输入：Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go DDD Scaffold API",
	Description:      "Go DDD Scaffold API 文档 - 基于 DDD 和 CQRS 的企业级脚手架",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
