// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query)
	CasbinRule       *casbinRule
	Tenant           *tenant
	TenantInvitation *tenantInvitation
	TenantMember     *tenantMember
	User             *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CasbinRule = &Q.CasbinRule
	Tenant = &Q.Tenant
	TenantInvitation = &Q.TenantInvitation
	TenantMember = &Q.TenantMember
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		CasbinRule:       newCasbinRule(db, opts...),
		Tenant:           newTenant(db, opts...),
		TenantInvitation: newTenantInvitation(db, opts...),
		TenantMember:     newTenantMember(db, opts...),
		User:             newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CasbinRule       casbinRule
	Tenant           tenant
	TenantInvitation tenantInvitation
	TenantMember     tenantMember
	User             user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		CasbinRule:       q.CasbinRule.clone(db),
		Tenant:           q.Tenant.clone(db),
		TenantInvitation: q.TenantInvitation.clone(db),
		TenantMember:     q.TenantMember.clone(db),
		User:             q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		CasbinRule:       q.CasbinRule.replaceDB(db),
		Tenant:           q.Tenant.replaceDB(db),
		TenantInvitation: q.TenantInvitation.replaceDB(db),
		TenantMember:     q.TenantMember.replaceDB(db),
		User:             q.User.replaceDB(db),
	}
}

type queryCtx struct {
	CasbinRule       *casbinRuleDo
	Tenant           *tenantDo
	TenantInvitation *tenantInvitationDo
	TenantMember     *tenantMemberDo
	User             *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CasbinRule:       q.CasbinRule.WithContext(ctx),
		Tenant:           q.Tenant.WithContext(ctx),
		TenantInvitation: q.TenantInvitation.WithContext(ctx),
		TenantMember:     q.TenantMember.WithContext(ctx),
		User:             q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
