// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newKgAcademicConcept(db *gorm.DB, opts ...gen.DOOption) kgAcademicConcept {
	_kgAcademicConcept := kgAcademicConcept{}

	_kgAcademicConcept.kgAcademicConceptDo.UseDB(db, opts...)
	_kgAcademicConcept.kgAcademicConceptDo.UseModel(&model.KgAcademicConcept{})

	tableName := _kgAcademicConcept.kgAcademicConceptDo.TableName()
	_kgAcademicConcept.ALL = field.NewAsterisk(tableName)
	_kgAcademicConcept.ID = field.NewString(tableName, "id")
	_kgAcademicConcept.Name = field.NewString(tableName, "name")
	_kgAcademicConcept.Level = field.NewString(tableName, "level")
	_kgAcademicConcept.Field = field.NewString(tableName, "field")
	_kgAcademicConcept.NodeID = field.NewString(tableName, "node_id")
	_kgAcademicConcept.Metadata = field.NewString(tableName, "metadata")
	_kgAcademicConcept.CreatedAt = field.NewTime(tableName, "created_at")
	_kgAcademicConcept.UpdatedAt = field.NewTime(tableName, "updated_at")

	_kgAcademicConcept.fillFieldMap()

	return _kgAcademicConcept
}

type kgAcademicConcept struct {
	kgAcademicConceptDo

	ALL       field.Asterisk
	ID        field.String // 学术概念唯一标识符
	Name      field.String // 概念名称 (e.g., "方程")
	Level     field.String // 学术层级 (e.g., "基础", "高级")
	Field     field.String // 所属学术领域 (e.g., "代数")
	NodeID    field.String // 关联的知识图谱节点ID，用于将学术概念与知识节点关联
	Metadata  field.String // 额外元数据
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (k kgAcademicConcept) Table(newTableName string) *kgAcademicConcept {
	k.kgAcademicConceptDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kgAcademicConcept) As(alias string) *kgAcademicConcept {
	k.kgAcademicConceptDo.DO = *(k.kgAcademicConceptDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kgAcademicConcept) updateTableName(table string) *kgAcademicConcept {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewString(table, "id")
	k.Name = field.NewString(table, "name")
	k.Level = field.NewString(table, "level")
	k.Field = field.NewString(table, "field")
	k.NodeID = field.NewString(table, "node_id")
	k.Metadata = field.NewString(table, "metadata")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *kgAcademicConcept) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kgAcademicConcept) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 8)
	k.fieldMap["id"] = k.ID
	k.fieldMap["name"] = k.Name
	k.fieldMap["level"] = k.Level
	k.fieldMap["field"] = k.Field
	k.fieldMap["node_id"] = k.NodeID
	k.fieldMap["metadata"] = k.Metadata
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k kgAcademicConcept) clone(db *gorm.DB) kgAcademicConcept {
	k.kgAcademicConceptDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kgAcademicConcept) replaceDB(db *gorm.DB) kgAcademicConcept {
	k.kgAcademicConceptDo.ReplaceDB(db)
	return k
}

type kgAcademicConceptDo struct{ gen.DO }

func (k kgAcademicConceptDo) Debug() *kgAcademicConceptDo {
	return k.withDO(k.DO.Debug())
}

func (k kgAcademicConceptDo) WithContext(ctx context.Context) *kgAcademicConceptDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kgAcademicConceptDo) ReadDB() *kgAcademicConceptDo {
	return k.Clauses(dbresolver.Read)
}

func (k kgAcademicConceptDo) WriteDB() *kgAcademicConceptDo {
	return k.Clauses(dbresolver.Write)
}

func (k kgAcademicConceptDo) Session(config *gorm.Session) *kgAcademicConceptDo {
	return k.withDO(k.DO.Session(config))
}

func (k kgAcademicConceptDo) Clauses(conds ...clause.Expression) *kgAcademicConceptDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kgAcademicConceptDo) Returning(value interface{}, columns ...string) *kgAcademicConceptDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kgAcademicConceptDo) Not(conds ...gen.Condition) *kgAcademicConceptDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kgAcademicConceptDo) Or(conds ...gen.Condition) *kgAcademicConceptDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kgAcademicConceptDo) Select(conds ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kgAcademicConceptDo) Where(conds ...gen.Condition) *kgAcademicConceptDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kgAcademicConceptDo) Order(conds ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kgAcademicConceptDo) Distinct(cols ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kgAcademicConceptDo) Omit(cols ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kgAcademicConceptDo) Join(table schema.Tabler, on ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kgAcademicConceptDo) LeftJoin(table schema.Tabler, on ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kgAcademicConceptDo) RightJoin(table schema.Tabler, on ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kgAcademicConceptDo) Group(cols ...field.Expr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kgAcademicConceptDo) Having(conds ...gen.Condition) *kgAcademicConceptDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kgAcademicConceptDo) Limit(limit int) *kgAcademicConceptDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kgAcademicConceptDo) Offset(offset int) *kgAcademicConceptDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kgAcademicConceptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *kgAcademicConceptDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kgAcademicConceptDo) Unscoped() *kgAcademicConceptDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kgAcademicConceptDo) Create(values ...*model.KgAcademicConcept) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kgAcademicConceptDo) CreateInBatches(values []*model.KgAcademicConcept, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kgAcademicConceptDo) Save(values ...*model.KgAcademicConcept) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kgAcademicConceptDo) First() (*model.KgAcademicConcept, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgAcademicConcept), nil
	}
}

func (k kgAcademicConceptDo) Take() (*model.KgAcademicConcept, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgAcademicConcept), nil
	}
}

func (k kgAcademicConceptDo) Last() (*model.KgAcademicConcept, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgAcademicConcept), nil
	}
}

func (k kgAcademicConceptDo) Find() ([]*model.KgAcademicConcept, error) {
	result, err := k.DO.Find()
	return result.([]*model.KgAcademicConcept), err
}

func (k kgAcademicConceptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KgAcademicConcept, err error) {
	buf := make([]*model.KgAcademicConcept, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kgAcademicConceptDo) FindInBatches(result *[]*model.KgAcademicConcept, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kgAcademicConceptDo) Attrs(attrs ...field.AssignExpr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kgAcademicConceptDo) Assign(attrs ...field.AssignExpr) *kgAcademicConceptDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kgAcademicConceptDo) Joins(fields ...field.RelationField) *kgAcademicConceptDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kgAcademicConceptDo) Preload(fields ...field.RelationField) *kgAcademicConceptDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kgAcademicConceptDo) FirstOrInit() (*model.KgAcademicConcept, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgAcademicConcept), nil
	}
}

func (k kgAcademicConceptDo) FirstOrCreate() (*model.KgAcademicConcept, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgAcademicConcept), nil
	}
}

func (k kgAcademicConceptDo) FindByPage(offset int, limit int) (result []*model.KgAcademicConcept, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kgAcademicConceptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kgAcademicConceptDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kgAcademicConceptDo) Delete(models ...*model.KgAcademicConcept) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kgAcademicConceptDo) withDO(do gen.Dao) *kgAcademicConceptDo {
	k.DO = *do.(*gen.DO)
	return k
}
