// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newKgCompetencyLevel(db *gorm.DB, opts ...gen.DOOption) kgCompetencyLevel {
	_kgCompetencyLevel := kgCompetencyLevel{}

	_kgCompetencyLevel.kgCompetencyLevelDo.UseDB(db, opts...)
	_kgCompetencyLevel.kgCompetencyLevelDo.UseModel(&model.KgCompetencyLevel{})

	tableName := _kgCompetencyLevel.kgCompetencyLevelDo.TableName()
	_kgCompetencyLevel.ALL = field.NewAsterisk(tableName)
	_kgCompetencyLevel.ID = field.NewString(tableName, "id")
	_kgCompetencyLevel.ModelName = field.NewString(tableName, "model_name")
	_kgCompetencyLevel.LevelValue = field.NewString(tableName, "level_value")
	_kgCompetencyLevel.DescriptionKey = field.NewString(tableName, "description_key")
	_kgCompetencyLevel.MinMasteryScore = field.NewFloat64(tableName, "min_mastery_score")
	_kgCompetencyLevel.NodeID = field.NewString(tableName, "node_id")
	_kgCompetencyLevel.Metadata = field.NewString(tableName, "metadata")
	_kgCompetencyLevel.CreatedAt = field.NewTime(tableName, "created_at")
	_kgCompetencyLevel.UpdatedAt = field.NewTime(tableName, "updated_at")

	_kgCompetencyLevel.fillFieldMap()

	return _kgCompetencyLevel
}

type kgCompetencyLevel struct {
	kgCompetencyLevelDo

	ALL             field.Asterisk
	ID              field.String  // 等级唯一标识符
	ModelName       field.String  // 等级模型名称 (e.g., "Bloom_SOLO_Fusion")
	LevelValue      field.String  // 级别值 (e.g., "Lv1", "Advanced")
	DescriptionKey  field.String  // 该级别描述的国际化键 (e.g., "levels.bloom_solo_fusion.lv1.description")
	MinMasteryScore field.Float64 // 触发此级别的最低掌握度阈值
	NodeID          field.String  // 关联的知识图谱节点ID，用于将能力等级与知识节点关联
	Metadata        field.String  // 额外元数据
	CreatedAt       field.Time    // 创建时间
	UpdatedAt       field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (k kgCompetencyLevel) Table(newTableName string) *kgCompetencyLevel {
	k.kgCompetencyLevelDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kgCompetencyLevel) As(alias string) *kgCompetencyLevel {
	k.kgCompetencyLevelDo.DO = *(k.kgCompetencyLevelDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kgCompetencyLevel) updateTableName(table string) *kgCompetencyLevel {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewString(table, "id")
	k.ModelName = field.NewString(table, "model_name")
	k.LevelValue = field.NewString(table, "level_value")
	k.DescriptionKey = field.NewString(table, "description_key")
	k.MinMasteryScore = field.NewFloat64(table, "min_mastery_score")
	k.NodeID = field.NewString(table, "node_id")
	k.Metadata = field.NewString(table, "metadata")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *kgCompetencyLevel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kgCompetencyLevel) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 9)
	k.fieldMap["id"] = k.ID
	k.fieldMap["model_name"] = k.ModelName
	k.fieldMap["level_value"] = k.LevelValue
	k.fieldMap["description_key"] = k.DescriptionKey
	k.fieldMap["min_mastery_score"] = k.MinMasteryScore
	k.fieldMap["node_id"] = k.NodeID
	k.fieldMap["metadata"] = k.Metadata
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k kgCompetencyLevel) clone(db *gorm.DB) kgCompetencyLevel {
	k.kgCompetencyLevelDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kgCompetencyLevel) replaceDB(db *gorm.DB) kgCompetencyLevel {
	k.kgCompetencyLevelDo.ReplaceDB(db)
	return k
}

type kgCompetencyLevelDo struct{ gen.DO }

func (k kgCompetencyLevelDo) Debug() *kgCompetencyLevelDo {
	return k.withDO(k.DO.Debug())
}

func (k kgCompetencyLevelDo) WithContext(ctx context.Context) *kgCompetencyLevelDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kgCompetencyLevelDo) ReadDB() *kgCompetencyLevelDo {
	return k.Clauses(dbresolver.Read)
}

func (k kgCompetencyLevelDo) WriteDB() *kgCompetencyLevelDo {
	return k.Clauses(dbresolver.Write)
}

func (k kgCompetencyLevelDo) Session(config *gorm.Session) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Session(config))
}

func (k kgCompetencyLevelDo) Clauses(conds ...clause.Expression) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kgCompetencyLevelDo) Returning(value interface{}, columns ...string) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kgCompetencyLevelDo) Not(conds ...gen.Condition) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kgCompetencyLevelDo) Or(conds ...gen.Condition) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kgCompetencyLevelDo) Select(conds ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kgCompetencyLevelDo) Where(conds ...gen.Condition) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kgCompetencyLevelDo) Order(conds ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kgCompetencyLevelDo) Distinct(cols ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kgCompetencyLevelDo) Omit(cols ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kgCompetencyLevelDo) Join(table schema.Tabler, on ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kgCompetencyLevelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kgCompetencyLevelDo) RightJoin(table schema.Tabler, on ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kgCompetencyLevelDo) Group(cols ...field.Expr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kgCompetencyLevelDo) Having(conds ...gen.Condition) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kgCompetencyLevelDo) Limit(limit int) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kgCompetencyLevelDo) Offset(offset int) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kgCompetencyLevelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kgCompetencyLevelDo) Unscoped() *kgCompetencyLevelDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kgCompetencyLevelDo) Create(values ...*model.KgCompetencyLevel) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kgCompetencyLevelDo) CreateInBatches(values []*model.KgCompetencyLevel, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kgCompetencyLevelDo) Save(values ...*model.KgCompetencyLevel) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kgCompetencyLevelDo) First() (*model.KgCompetencyLevel, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgCompetencyLevel), nil
	}
}

func (k kgCompetencyLevelDo) Take() (*model.KgCompetencyLevel, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgCompetencyLevel), nil
	}
}

func (k kgCompetencyLevelDo) Last() (*model.KgCompetencyLevel, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgCompetencyLevel), nil
	}
}

func (k kgCompetencyLevelDo) Find() ([]*model.KgCompetencyLevel, error) {
	result, err := k.DO.Find()
	return result.([]*model.KgCompetencyLevel), err
}

func (k kgCompetencyLevelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KgCompetencyLevel, err error) {
	buf := make([]*model.KgCompetencyLevel, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kgCompetencyLevelDo) FindInBatches(result *[]*model.KgCompetencyLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kgCompetencyLevelDo) Attrs(attrs ...field.AssignExpr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kgCompetencyLevelDo) Assign(attrs ...field.AssignExpr) *kgCompetencyLevelDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kgCompetencyLevelDo) Joins(fields ...field.RelationField) *kgCompetencyLevelDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kgCompetencyLevelDo) Preload(fields ...field.RelationField) *kgCompetencyLevelDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kgCompetencyLevelDo) FirstOrInit() (*model.KgCompetencyLevel, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgCompetencyLevel), nil
	}
}

func (k kgCompetencyLevelDo) FirstOrCreate() (*model.KgCompetencyLevel, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgCompetencyLevel), nil
	}
}

func (k kgCompetencyLevelDo) FindByPage(offset int, limit int) (result []*model.KgCompetencyLevel, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kgCompetencyLevelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kgCompetencyLevelDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kgCompetencyLevelDo) Delete(models ...*model.KgCompetencyLevel) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kgCompetencyLevelDo) withDO(do gen.Dao) *kgCompetencyLevelDo {
	k.DO = *do.(*gen.DO)
	return k
}
