// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newKgDomain(db *gorm.DB, opts ...gen.DOOption) kgDomain {
	_kgDomain := kgDomain{}

	_kgDomain.kgDomainDo.UseDB(db, opts...)
	_kgDomain.kgDomainDo.UseModel(&model.KgDomain{})

	tableName := _kgDomain.kgDomainDo.TableName()
	_kgDomain.ALL = field.NewAsterisk(tableName)
	_kgDomain.ID = field.NewString(tableName, "id")
	_kgDomain.NameKey = field.NewString(tableName, "name_key")
	_kgDomain.DescriptionKey = field.NewString(tableName, "description_key")
	_kgDomain.WorldViewType = field.NewString(tableName, "world_view_type")
	_kgDomain.WorldViewConfig = field.NewString(tableName, "world_view_config")
	_kgDomain.AcademicSource = field.NewString(tableName, "academic_source")
	_kgDomain.IsActive = field.NewBool(tableName, "is_active")
	_kgDomain.Metadata = field.NewString(tableName, "metadata")
	_kgDomain.CreatedAt = field.NewTime(tableName, "created_at")
	_kgDomain.UpdatedAt = field.NewTime(tableName, "updated_at")

	_kgDomain.fillFieldMap()

	return _kgDomain
}

type kgDomain struct {
	kgDomainDo

	ALL             field.Asterisk
	ID              field.String // 领域唯一标识符
	NameKey         field.String // 名称的国际化键 (e.g., "domains.numeracy_algebra.name")
	DescriptionKey  field.String // 描述的国际化键 (e.g., "domains.numeracy_algebra.description")
	WorldViewType   field.String // 领域的世界观类型 (e.g., "FOUNDATION_BUILDING", "PUBLIC_SQUARE")
	WorldViewConfig field.String // 世界观相关的配置信息
	AcademicSource  field.String // 学术源头 (e.g., "基础数学/代数")
	IsActive        field.Bool   // 是否激活，默认 True
	Metadata        field.String // 额外元数据
	CreatedAt       field.Time   // 创建时间
	UpdatedAt       field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (k kgDomain) Table(newTableName string) *kgDomain {
	k.kgDomainDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kgDomain) As(alias string) *kgDomain {
	k.kgDomainDo.DO = *(k.kgDomainDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kgDomain) updateTableName(table string) *kgDomain {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewString(table, "id")
	k.NameKey = field.NewString(table, "name_key")
	k.DescriptionKey = field.NewString(table, "description_key")
	k.WorldViewType = field.NewString(table, "world_view_type")
	k.WorldViewConfig = field.NewString(table, "world_view_config")
	k.AcademicSource = field.NewString(table, "academic_source")
	k.IsActive = field.NewBool(table, "is_active")
	k.Metadata = field.NewString(table, "metadata")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")

	k.fillFieldMap()

	return k
}

func (k *kgDomain) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kgDomain) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 10)
	k.fieldMap["id"] = k.ID
	k.fieldMap["name_key"] = k.NameKey
	k.fieldMap["description_key"] = k.DescriptionKey
	k.fieldMap["world_view_type"] = k.WorldViewType
	k.fieldMap["world_view_config"] = k.WorldViewConfig
	k.fieldMap["academic_source"] = k.AcademicSource
	k.fieldMap["is_active"] = k.IsActive
	k.fieldMap["metadata"] = k.Metadata
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
}

func (k kgDomain) clone(db *gorm.DB) kgDomain {
	k.kgDomainDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kgDomain) replaceDB(db *gorm.DB) kgDomain {
	k.kgDomainDo.ReplaceDB(db)
	return k
}

type kgDomainDo struct{ gen.DO }

func (k kgDomainDo) Debug() *kgDomainDo {
	return k.withDO(k.DO.Debug())
}

func (k kgDomainDo) WithContext(ctx context.Context) *kgDomainDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kgDomainDo) ReadDB() *kgDomainDo {
	return k.Clauses(dbresolver.Read)
}

func (k kgDomainDo) WriteDB() *kgDomainDo {
	return k.Clauses(dbresolver.Write)
}

func (k kgDomainDo) Session(config *gorm.Session) *kgDomainDo {
	return k.withDO(k.DO.Session(config))
}

func (k kgDomainDo) Clauses(conds ...clause.Expression) *kgDomainDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kgDomainDo) Returning(value interface{}, columns ...string) *kgDomainDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kgDomainDo) Not(conds ...gen.Condition) *kgDomainDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kgDomainDo) Or(conds ...gen.Condition) *kgDomainDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kgDomainDo) Select(conds ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kgDomainDo) Where(conds ...gen.Condition) *kgDomainDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kgDomainDo) Order(conds ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kgDomainDo) Distinct(cols ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kgDomainDo) Omit(cols ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kgDomainDo) Join(table schema.Tabler, on ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kgDomainDo) LeftJoin(table schema.Tabler, on ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kgDomainDo) RightJoin(table schema.Tabler, on ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kgDomainDo) Group(cols ...field.Expr) *kgDomainDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kgDomainDo) Having(conds ...gen.Condition) *kgDomainDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kgDomainDo) Limit(limit int) *kgDomainDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kgDomainDo) Offset(offset int) *kgDomainDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kgDomainDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *kgDomainDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kgDomainDo) Unscoped() *kgDomainDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kgDomainDo) Create(values ...*model.KgDomain) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kgDomainDo) CreateInBatches(values []*model.KgDomain, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kgDomainDo) Save(values ...*model.KgDomain) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kgDomainDo) First() (*model.KgDomain, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgDomain), nil
	}
}

func (k kgDomainDo) Take() (*model.KgDomain, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgDomain), nil
	}
}

func (k kgDomainDo) Last() (*model.KgDomain, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgDomain), nil
	}
}

func (k kgDomainDo) Find() ([]*model.KgDomain, error) {
	result, err := k.DO.Find()
	return result.([]*model.KgDomain), err
}

func (k kgDomainDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KgDomain, err error) {
	buf := make([]*model.KgDomain, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kgDomainDo) FindInBatches(result *[]*model.KgDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kgDomainDo) Attrs(attrs ...field.AssignExpr) *kgDomainDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kgDomainDo) Assign(attrs ...field.AssignExpr) *kgDomainDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kgDomainDo) Joins(fields ...field.RelationField) *kgDomainDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kgDomainDo) Preload(fields ...field.RelationField) *kgDomainDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kgDomainDo) FirstOrInit() (*model.KgDomain, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgDomain), nil
	}
}

func (k kgDomainDo) FirstOrCreate() (*model.KgDomain, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KgDomain), nil
	}
}

func (k kgDomainDo) FindByPage(offset int, limit int) (result []*model.KgDomain, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kgDomainDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kgDomainDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kgDomainDo) Delete(models ...*model.KgDomain) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kgDomainDo) withDO(do gen.Dao) *kgDomainDo {
	k.DO = *do.(*gen.DO)
	return k
}
