// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newLearnAssessmentItem(db *gorm.DB, opts ...gen.DOOption) learnAssessmentItem {
	_learnAssessmentItem := learnAssessmentItem{}

	_learnAssessmentItem.learnAssessmentItemDo.UseDB(db, opts...)
	_learnAssessmentItem.learnAssessmentItemDo.UseModel(&model.LearnAssessmentItem{})

	tableName := _learnAssessmentItem.learnAssessmentItemDo.TableName()
	_learnAssessmentItem.ALL = field.NewAsterisk(tableName)
	_learnAssessmentItem.ID = field.NewString(tableName, "id")
	_learnAssessmentItem.QuestionTextKey = field.NewString(tableName, "question_text_key")
	_learnAssessmentItem.CorrectAnswer = field.NewString(tableName, "correct_answer")
	_learnAssessmentItem.DifficultyLevel = field.NewString(tableName, "difficulty_level")
	_learnAssessmentItem.IsActive = field.NewBool(tableName, "is_active")
	_learnAssessmentItem.Metadata = field.NewString(tableName, "metadata")
	_learnAssessmentItem.CreatedAt = field.NewTime(tableName, "created_at")
	_learnAssessmentItem.UpdatedAt = field.NewTime(tableName, "updated_at")

	_learnAssessmentItem.fillFieldMap()

	return _learnAssessmentItem
}

type learnAssessmentItem struct {
	learnAssessmentItemDo

	ALL             field.Asterisk
	ID              field.String
	QuestionTextKey field.String
	CorrectAnswer   field.String
	DifficultyLevel field.String
	IsActive        field.Bool
	Metadata        field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (l learnAssessmentItem) Table(newTableName string) *learnAssessmentItem {
	l.learnAssessmentItemDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l learnAssessmentItem) As(alias string) *learnAssessmentItem {
	l.learnAssessmentItemDo.DO = *(l.learnAssessmentItemDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *learnAssessmentItem) updateTableName(table string) *learnAssessmentItem {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.QuestionTextKey = field.NewString(table, "question_text_key")
	l.CorrectAnswer = field.NewString(table, "correct_answer")
	l.DifficultyLevel = field.NewString(table, "difficulty_level")
	l.IsActive = field.NewBool(table, "is_active")
	l.Metadata = field.NewString(table, "metadata")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *learnAssessmentItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *learnAssessmentItem) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 8)
	l.fieldMap["id"] = l.ID
	l.fieldMap["question_text_key"] = l.QuestionTextKey
	l.fieldMap["correct_answer"] = l.CorrectAnswer
	l.fieldMap["difficulty_level"] = l.DifficultyLevel
	l.fieldMap["is_active"] = l.IsActive
	l.fieldMap["metadata"] = l.Metadata
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l learnAssessmentItem) clone(db *gorm.DB) learnAssessmentItem {
	l.learnAssessmentItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l learnAssessmentItem) replaceDB(db *gorm.DB) learnAssessmentItem {
	l.learnAssessmentItemDo.ReplaceDB(db)
	return l
}

type learnAssessmentItemDo struct{ gen.DO }

func (l learnAssessmentItemDo) Debug() *learnAssessmentItemDo {
	return l.withDO(l.DO.Debug())
}

func (l learnAssessmentItemDo) WithContext(ctx context.Context) *learnAssessmentItemDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l learnAssessmentItemDo) ReadDB() *learnAssessmentItemDo {
	return l.Clauses(dbresolver.Read)
}

func (l learnAssessmentItemDo) WriteDB() *learnAssessmentItemDo {
	return l.Clauses(dbresolver.Write)
}

func (l learnAssessmentItemDo) Session(config *gorm.Session) *learnAssessmentItemDo {
	return l.withDO(l.DO.Session(config))
}

func (l learnAssessmentItemDo) Clauses(conds ...clause.Expression) *learnAssessmentItemDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l learnAssessmentItemDo) Returning(value interface{}, columns ...string) *learnAssessmentItemDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l learnAssessmentItemDo) Not(conds ...gen.Condition) *learnAssessmentItemDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l learnAssessmentItemDo) Or(conds ...gen.Condition) *learnAssessmentItemDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l learnAssessmentItemDo) Select(conds ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l learnAssessmentItemDo) Where(conds ...gen.Condition) *learnAssessmentItemDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l learnAssessmentItemDo) Order(conds ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l learnAssessmentItemDo) Distinct(cols ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l learnAssessmentItemDo) Omit(cols ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l learnAssessmentItemDo) Join(table schema.Tabler, on ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l learnAssessmentItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l learnAssessmentItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l learnAssessmentItemDo) Group(cols ...field.Expr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l learnAssessmentItemDo) Having(conds ...gen.Condition) *learnAssessmentItemDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l learnAssessmentItemDo) Limit(limit int) *learnAssessmentItemDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l learnAssessmentItemDo) Offset(offset int) *learnAssessmentItemDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l learnAssessmentItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *learnAssessmentItemDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l learnAssessmentItemDo) Unscoped() *learnAssessmentItemDo {
	return l.withDO(l.DO.Unscoped())
}

func (l learnAssessmentItemDo) Create(values ...*model.LearnAssessmentItem) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l learnAssessmentItemDo) CreateInBatches(values []*model.LearnAssessmentItem, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l learnAssessmentItemDo) Save(values ...*model.LearnAssessmentItem) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l learnAssessmentItemDo) First() (*model.LearnAssessmentItem, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnAssessmentItem), nil
	}
}

func (l learnAssessmentItemDo) Take() (*model.LearnAssessmentItem, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnAssessmentItem), nil
	}
}

func (l learnAssessmentItemDo) Last() (*model.LearnAssessmentItem, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnAssessmentItem), nil
	}
}

func (l learnAssessmentItemDo) Find() ([]*model.LearnAssessmentItem, error) {
	result, err := l.DO.Find()
	return result.([]*model.LearnAssessmentItem), err
}

func (l learnAssessmentItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LearnAssessmentItem, err error) {
	buf := make([]*model.LearnAssessmentItem, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l learnAssessmentItemDo) FindInBatches(result *[]*model.LearnAssessmentItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l learnAssessmentItemDo) Attrs(attrs ...field.AssignExpr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l learnAssessmentItemDo) Assign(attrs ...field.AssignExpr) *learnAssessmentItemDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l learnAssessmentItemDo) Joins(fields ...field.RelationField) *learnAssessmentItemDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l learnAssessmentItemDo) Preload(fields ...field.RelationField) *learnAssessmentItemDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l learnAssessmentItemDo) FirstOrInit() (*model.LearnAssessmentItem, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnAssessmentItem), nil
	}
}

func (l learnAssessmentItemDo) FirstOrCreate() (*model.LearnAssessmentItem, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnAssessmentItem), nil
	}
}

func (l learnAssessmentItemDo) FindByPage(offset int, limit int) (result []*model.LearnAssessmentItem, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l learnAssessmentItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l learnAssessmentItemDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l learnAssessmentItemDo) Delete(models ...*model.LearnAssessmentItem) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *learnAssessmentItemDo) withDO(do gen.Dao) *learnAssessmentItemDo {
	l.DO = *do.(*gen.DO)
	return l
}
