// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newLearnStudentProgress(db *gorm.DB, opts ...gen.DOOption) learnStudentProgress {
	_learnStudentProgress := learnStudentProgress{}

	_learnStudentProgress.learnStudentProgressDo.UseDB(db, opts...)
	_learnStudentProgress.learnStudentProgressDo.UseModel(&model.LearnStudentProgress{})

	tableName := _learnStudentProgress.learnStudentProgressDo.TableName()
	_learnStudentProgress.ALL = field.NewAsterisk(tableName)
	_learnStudentProgress.ID = field.NewString(tableName, "id")
	_learnStudentProgress.StudentID = field.NewString(tableName, "student_id")
	_learnStudentProgress.NodeID = field.NewString(tableName, "node_id")
	_learnStudentProgress.MasteryScore = field.NewFloat64(tableName, "mastery_score")
	_learnStudentProgress.LastInteractedAt = field.NewTime(tableName, "last_interacted_at")
	_learnStudentProgress.AttemptsCount = field.NewInt32(tableName, "attempts_count")
	_learnStudentProgress.Metadata = field.NewString(tableName, "metadata")
	_learnStudentProgress.CreatedAt = field.NewTime(tableName, "created_at")
	_learnStudentProgress.UpdatedAt = field.NewTime(tableName, "updated_at")

	_learnStudentProgress.fillFieldMap()

	return _learnStudentProgress
}

type learnStudentProgress struct {
	learnStudentProgressDo

	ALL              field.Asterisk
	ID               field.String
	StudentID        field.String
	NodeID           field.String
	MasteryScore     field.Float64
	LastInteractedAt field.Time
	AttemptsCount    field.Int32
	Metadata         field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (l learnStudentProgress) Table(newTableName string) *learnStudentProgress {
	l.learnStudentProgressDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l learnStudentProgress) As(alias string) *learnStudentProgress {
	l.learnStudentProgressDo.DO = *(l.learnStudentProgressDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *learnStudentProgress) updateTableName(table string) *learnStudentProgress {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.StudentID = field.NewString(table, "student_id")
	l.NodeID = field.NewString(table, "node_id")
	l.MasteryScore = field.NewFloat64(table, "mastery_score")
	l.LastInteractedAt = field.NewTime(table, "last_interacted_at")
	l.AttemptsCount = field.NewInt32(table, "attempts_count")
	l.Metadata = field.NewString(table, "metadata")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *learnStudentProgress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *learnStudentProgress) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 9)
	l.fieldMap["id"] = l.ID
	l.fieldMap["student_id"] = l.StudentID
	l.fieldMap["node_id"] = l.NodeID
	l.fieldMap["mastery_score"] = l.MasteryScore
	l.fieldMap["last_interacted_at"] = l.LastInteractedAt
	l.fieldMap["attempts_count"] = l.AttemptsCount
	l.fieldMap["metadata"] = l.Metadata
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l learnStudentProgress) clone(db *gorm.DB) learnStudentProgress {
	l.learnStudentProgressDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l learnStudentProgress) replaceDB(db *gorm.DB) learnStudentProgress {
	l.learnStudentProgressDo.ReplaceDB(db)
	return l
}

type learnStudentProgressDo struct{ gen.DO }

func (l learnStudentProgressDo) Debug() *learnStudentProgressDo {
	return l.withDO(l.DO.Debug())
}

func (l learnStudentProgressDo) WithContext(ctx context.Context) *learnStudentProgressDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l learnStudentProgressDo) ReadDB() *learnStudentProgressDo {
	return l.Clauses(dbresolver.Read)
}

func (l learnStudentProgressDo) WriteDB() *learnStudentProgressDo {
	return l.Clauses(dbresolver.Write)
}

func (l learnStudentProgressDo) Session(config *gorm.Session) *learnStudentProgressDo {
	return l.withDO(l.DO.Session(config))
}

func (l learnStudentProgressDo) Clauses(conds ...clause.Expression) *learnStudentProgressDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l learnStudentProgressDo) Returning(value interface{}, columns ...string) *learnStudentProgressDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l learnStudentProgressDo) Not(conds ...gen.Condition) *learnStudentProgressDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l learnStudentProgressDo) Or(conds ...gen.Condition) *learnStudentProgressDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l learnStudentProgressDo) Select(conds ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l learnStudentProgressDo) Where(conds ...gen.Condition) *learnStudentProgressDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l learnStudentProgressDo) Order(conds ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l learnStudentProgressDo) Distinct(cols ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l learnStudentProgressDo) Omit(cols ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l learnStudentProgressDo) Join(table schema.Tabler, on ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l learnStudentProgressDo) LeftJoin(table schema.Tabler, on ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l learnStudentProgressDo) RightJoin(table schema.Tabler, on ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l learnStudentProgressDo) Group(cols ...field.Expr) *learnStudentProgressDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l learnStudentProgressDo) Having(conds ...gen.Condition) *learnStudentProgressDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l learnStudentProgressDo) Limit(limit int) *learnStudentProgressDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l learnStudentProgressDo) Offset(offset int) *learnStudentProgressDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l learnStudentProgressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *learnStudentProgressDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l learnStudentProgressDo) Unscoped() *learnStudentProgressDo {
	return l.withDO(l.DO.Unscoped())
}

func (l learnStudentProgressDo) Create(values ...*model.LearnStudentProgress) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l learnStudentProgressDo) CreateInBatches(values []*model.LearnStudentProgress, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l learnStudentProgressDo) Save(values ...*model.LearnStudentProgress) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l learnStudentProgressDo) First() (*model.LearnStudentProgress, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnStudentProgress), nil
	}
}

func (l learnStudentProgressDo) Take() (*model.LearnStudentProgress, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnStudentProgress), nil
	}
}

func (l learnStudentProgressDo) Last() (*model.LearnStudentProgress, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnStudentProgress), nil
	}
}

func (l learnStudentProgressDo) Find() ([]*model.LearnStudentProgress, error) {
	result, err := l.DO.Find()
	return result.([]*model.LearnStudentProgress), err
}

func (l learnStudentProgressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LearnStudentProgress, err error) {
	buf := make([]*model.LearnStudentProgress, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l learnStudentProgressDo) FindInBatches(result *[]*model.LearnStudentProgress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l learnStudentProgressDo) Attrs(attrs ...field.AssignExpr) *learnStudentProgressDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l learnStudentProgressDo) Assign(attrs ...field.AssignExpr) *learnStudentProgressDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l learnStudentProgressDo) Joins(fields ...field.RelationField) *learnStudentProgressDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l learnStudentProgressDo) Preload(fields ...field.RelationField) *learnStudentProgressDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l learnStudentProgressDo) FirstOrInit() (*model.LearnStudentProgress, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnStudentProgress), nil
	}
}

func (l learnStudentProgressDo) FirstOrCreate() (*model.LearnStudentProgress, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnStudentProgress), nil
	}
}

func (l learnStudentProgressDo) FindByPage(offset int, limit int) (result []*model.LearnStudentProgress, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l learnStudentProgressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l learnStudentProgressDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l learnStudentProgressDo) Delete(models ...*model.LearnStudentProgress) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *learnStudentProgressDo) withDO(do gen.Dao) *learnStudentProgressDo {
	l.DO = *do.(*gen.DO)
	return l
}
