// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newLearnSideQuest(db *gorm.DB, opts ...gen.DOOption) learnSideQuest {
	_learnSideQuest := learnSideQuest{}

	_learnSideQuest.learnSideQuestDo.UseDB(db, opts...)
	_learnSideQuest.learnSideQuestDo.UseModel(&model.LearnSideQuest{})

	tableName := _learnSideQuest.learnSideQuestDo.TableName()
	_learnSideQuest.ALL = field.NewAsterisk(tableName)
	_learnSideQuest.ID = field.NewString(tableName, "id")
	_learnSideQuest.NameKey = field.NewString(tableName, "name_key")
	_learnSideQuest.DescriptionKey = field.NewString(tableName, "description_key")
	_learnSideQuest.TargetNodeID = field.NewString(tableName, "target_node_id")
	_learnSideQuest.Category = field.NewString(tableName, "category")
	_learnSideQuest.DifficultyLevel = field.NewString(tableName, "difficulty_level")
	_learnSideQuest.Weight = field.NewFloat64(tableName, "weight")
	_learnSideQuest.TriggerConditionJSON = field.NewString(tableName, "trigger_condition_json")
	_learnSideQuest.Content = field.NewString(tableName, "content")
	_learnSideQuest.Reward = field.NewString(tableName, "reward")
	_learnSideQuest.IsActive = field.NewBool(tableName, "is_active")
	_learnSideQuest.Metadata = field.NewString(tableName, "metadata")
	_learnSideQuest.CreatedAt = field.NewTime(tableName, "created_at")
	_learnSideQuest.UpdatedAt = field.NewTime(tableName, "updated_at")

	_learnSideQuest.fillFieldMap()

	return _learnSideQuest
}

type learnSideQuest struct {
	learnSideQuestDo

	ALL                  field.Asterisk
	ID                   field.String
	NameKey              field.String
	DescriptionKey       field.String
	TargetNodeID         field.String
	Category             field.String
	DifficultyLevel      field.String
	Weight               field.Float64
	TriggerConditionJSON field.String
	Content              field.String
	Reward               field.String
	IsActive             field.Bool
	Metadata             field.String
	CreatedAt            field.Time
	UpdatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (l learnSideQuest) Table(newTableName string) *learnSideQuest {
	l.learnSideQuestDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l learnSideQuest) As(alias string) *learnSideQuest {
	l.learnSideQuestDo.DO = *(l.learnSideQuestDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *learnSideQuest) updateTableName(table string) *learnSideQuest {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.NameKey = field.NewString(table, "name_key")
	l.DescriptionKey = field.NewString(table, "description_key")
	l.TargetNodeID = field.NewString(table, "target_node_id")
	l.Category = field.NewString(table, "category")
	l.DifficultyLevel = field.NewString(table, "difficulty_level")
	l.Weight = field.NewFloat64(table, "weight")
	l.TriggerConditionJSON = field.NewString(table, "trigger_condition_json")
	l.Content = field.NewString(table, "content")
	l.Reward = field.NewString(table, "reward")
	l.IsActive = field.NewBool(table, "is_active")
	l.Metadata = field.NewString(table, "metadata")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *learnSideQuest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *learnSideQuest) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 14)
	l.fieldMap["id"] = l.ID
	l.fieldMap["name_key"] = l.NameKey
	l.fieldMap["description_key"] = l.DescriptionKey
	l.fieldMap["target_node_id"] = l.TargetNodeID
	l.fieldMap["category"] = l.Category
	l.fieldMap["difficulty_level"] = l.DifficultyLevel
	l.fieldMap["weight"] = l.Weight
	l.fieldMap["trigger_condition_json"] = l.TriggerConditionJSON
	l.fieldMap["content"] = l.Content
	l.fieldMap["reward"] = l.Reward
	l.fieldMap["is_active"] = l.IsActive
	l.fieldMap["metadata"] = l.Metadata
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l learnSideQuest) clone(db *gorm.DB) learnSideQuest {
	l.learnSideQuestDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l learnSideQuest) replaceDB(db *gorm.DB) learnSideQuest {
	l.learnSideQuestDo.ReplaceDB(db)
	return l
}

type learnSideQuestDo struct{ gen.DO }

func (l learnSideQuestDo) Debug() *learnSideQuestDo {
	return l.withDO(l.DO.Debug())
}

func (l learnSideQuestDo) WithContext(ctx context.Context) *learnSideQuestDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l learnSideQuestDo) ReadDB() *learnSideQuestDo {
	return l.Clauses(dbresolver.Read)
}

func (l learnSideQuestDo) WriteDB() *learnSideQuestDo {
	return l.Clauses(dbresolver.Write)
}

func (l learnSideQuestDo) Session(config *gorm.Session) *learnSideQuestDo {
	return l.withDO(l.DO.Session(config))
}

func (l learnSideQuestDo) Clauses(conds ...clause.Expression) *learnSideQuestDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l learnSideQuestDo) Returning(value interface{}, columns ...string) *learnSideQuestDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l learnSideQuestDo) Not(conds ...gen.Condition) *learnSideQuestDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l learnSideQuestDo) Or(conds ...gen.Condition) *learnSideQuestDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l learnSideQuestDo) Select(conds ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l learnSideQuestDo) Where(conds ...gen.Condition) *learnSideQuestDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l learnSideQuestDo) Order(conds ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l learnSideQuestDo) Distinct(cols ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l learnSideQuestDo) Omit(cols ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l learnSideQuestDo) Join(table schema.Tabler, on ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l learnSideQuestDo) LeftJoin(table schema.Tabler, on ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l learnSideQuestDo) RightJoin(table schema.Tabler, on ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l learnSideQuestDo) Group(cols ...field.Expr) *learnSideQuestDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l learnSideQuestDo) Having(conds ...gen.Condition) *learnSideQuestDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l learnSideQuestDo) Limit(limit int) *learnSideQuestDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l learnSideQuestDo) Offset(offset int) *learnSideQuestDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l learnSideQuestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *learnSideQuestDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l learnSideQuestDo) Unscoped() *learnSideQuestDo {
	return l.withDO(l.DO.Unscoped())
}

func (l learnSideQuestDo) Create(values ...*model.LearnSideQuest) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l learnSideQuestDo) CreateInBatches(values []*model.LearnSideQuest, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l learnSideQuestDo) Save(values ...*model.LearnSideQuest) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l learnSideQuestDo) First() (*model.LearnSideQuest, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnSideQuest), nil
	}
}

func (l learnSideQuestDo) Take() (*model.LearnSideQuest, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnSideQuest), nil
	}
}

func (l learnSideQuestDo) Last() (*model.LearnSideQuest, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnSideQuest), nil
	}
}

func (l learnSideQuestDo) Find() ([]*model.LearnSideQuest, error) {
	result, err := l.DO.Find()
	return result.([]*model.LearnSideQuest), err
}

func (l learnSideQuestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LearnSideQuest, err error) {
	buf := make([]*model.LearnSideQuest, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l learnSideQuestDo) FindInBatches(result *[]*model.LearnSideQuest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l learnSideQuestDo) Attrs(attrs ...field.AssignExpr) *learnSideQuestDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l learnSideQuestDo) Assign(attrs ...field.AssignExpr) *learnSideQuestDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l learnSideQuestDo) Joins(fields ...field.RelationField) *learnSideQuestDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l learnSideQuestDo) Preload(fields ...field.RelationField) *learnSideQuestDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l learnSideQuestDo) FirstOrInit() (*model.LearnSideQuest, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnSideQuest), nil
	}
}

func (l learnSideQuestDo) FirstOrCreate() (*model.LearnSideQuest, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LearnSideQuest), nil
	}
}

func (l learnSideQuestDo) FindByPage(offset int, limit int) (result []*model.LearnSideQuest, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l learnSideQuestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l learnSideQuestDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l learnSideQuestDo) Delete(models ...*model.LearnSideQuest) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *learnSideQuestDo) withDO(do gen.Dao) *learnSideQuestDo {
	l.DO = *do.(*gen.DO)
	return l
}
