// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newLoginLog(db *gorm.DB, opts ...gen.DOOption) loginLog {
	_loginLog := loginLog{}

	_loginLog.loginLogDo.UseDB(db, opts...)
	_loginLog.loginLogDo.UseModel(&model.LoginLog{})

	tableName := _loginLog.loginLogDo.TableName()
	_loginLog.ALL = field.NewAsterisk(tableName)
	_loginLog.ID = field.NewString(tableName, "id")
	_loginLog.UserID = field.NewString(tableName, "user_id")
	_loginLog.IPAddress = field.NewString(tableName, "ip_address")
	_loginLog.IPCountry = field.NewString(tableName, "ip_country")
	_loginLog.IPRegion = field.NewString(tableName, "ip_region")
	_loginLog.IPCity = field.NewString(tableName, "ip_city")
	_loginLog.DeviceType = field.NewString(tableName, "device_type")
	_loginLog.OsInfo = field.NewString(tableName, "os_info")
	_loginLog.BrowserInfo = field.NewString(tableName, "browser_info")
	_loginLog.LoginStatus = field.NewString(tableName, "login_status")
	_loginLog.FailureReason = field.NewString(tableName, "failure_reason")
	_loginLog.LoggedAt = field.NewTime(tableName, "logged_at")
	_loginLog.CreatedAt = field.NewTime(tableName, "created_at")

	_loginLog.fillFieldMap()

	return _loginLog
}

type loginLog struct {
	loginLogDo

	ALL           field.Asterisk
	ID            field.String
	UserID        field.String // 用户 ID，关联 users 表
	IPAddress     field.String // 登录 IP 地址（支持 IPv6）
	IPCountry     field.String // IP 归属国家（通过 IP 库解析）
	IPRegion      field.String // IP 归属省份/州
	IPCity        field.String // IP 归属城市
	DeviceType    field.String // 设备类型：mobile/desktop/tablet
	OsInfo        field.String // 操作系统信息（如：Windows 11, macOS 14.2）
	BrowserInfo   field.String // 浏览器信息（如：Chrome 120.0, Safari 17.2）
	LoginStatus   field.String // 登录状态：success/failed
	FailureReason field.String // 失败原因：wrong_password/account_locked/too_many_attempts 等
	LoggedAt      field.Time   // 登录发生时间
	CreatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (l loginLog) Table(newTableName string) *loginLog {
	l.loginLogDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loginLog) As(alias string) *loginLog {
	l.loginLogDo.DO = *(l.loginLogDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loginLog) updateTableName(table string) *loginLog {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewString(table, "id")
	l.UserID = field.NewString(table, "user_id")
	l.IPAddress = field.NewString(table, "ip_address")
	l.IPCountry = field.NewString(table, "ip_country")
	l.IPRegion = field.NewString(table, "ip_region")
	l.IPCity = field.NewString(table, "ip_city")
	l.DeviceType = field.NewString(table, "device_type")
	l.OsInfo = field.NewString(table, "os_info")
	l.BrowserInfo = field.NewString(table, "browser_info")
	l.LoginStatus = field.NewString(table, "login_status")
	l.FailureReason = field.NewString(table, "failure_reason")
	l.LoggedAt = field.NewTime(table, "logged_at")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *loginLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loginLog) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 13)
	l.fieldMap["id"] = l.ID
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["ip_address"] = l.IPAddress
	l.fieldMap["ip_country"] = l.IPCountry
	l.fieldMap["ip_region"] = l.IPRegion
	l.fieldMap["ip_city"] = l.IPCity
	l.fieldMap["device_type"] = l.DeviceType
	l.fieldMap["os_info"] = l.OsInfo
	l.fieldMap["browser_info"] = l.BrowserInfo
	l.fieldMap["login_status"] = l.LoginStatus
	l.fieldMap["failure_reason"] = l.FailureReason
	l.fieldMap["logged_at"] = l.LoggedAt
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l loginLog) clone(db *gorm.DB) loginLog {
	l.loginLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l loginLog) replaceDB(db *gorm.DB) loginLog {
	l.loginLogDo.ReplaceDB(db)
	return l
}

type loginLogDo struct{ gen.DO }

func (l loginLogDo) Debug() *loginLogDo {
	return l.withDO(l.DO.Debug())
}

func (l loginLogDo) WithContext(ctx context.Context) *loginLogDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loginLogDo) ReadDB() *loginLogDo {
	return l.Clauses(dbresolver.Read)
}

func (l loginLogDo) WriteDB() *loginLogDo {
	return l.Clauses(dbresolver.Write)
}

func (l loginLogDo) Session(config *gorm.Session) *loginLogDo {
	return l.withDO(l.DO.Session(config))
}

func (l loginLogDo) Clauses(conds ...clause.Expression) *loginLogDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loginLogDo) Returning(value interface{}, columns ...string) *loginLogDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loginLogDo) Not(conds ...gen.Condition) *loginLogDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loginLogDo) Or(conds ...gen.Condition) *loginLogDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loginLogDo) Select(conds ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loginLogDo) Where(conds ...gen.Condition) *loginLogDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loginLogDo) Order(conds ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loginLogDo) Distinct(cols ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loginLogDo) Omit(cols ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loginLogDo) Join(table schema.Tabler, on ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loginLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loginLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loginLogDo) Group(cols ...field.Expr) *loginLogDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loginLogDo) Having(conds ...gen.Condition) *loginLogDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loginLogDo) Limit(limit int) *loginLogDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loginLogDo) Offset(offset int) *loginLogDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loginLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loginLogDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loginLogDo) Unscoped() *loginLogDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loginLogDo) Create(values ...*model.LoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loginLogDo) CreateInBatches(values []*model.LoginLog, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loginLogDo) Save(values ...*model.LoginLog) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loginLogDo) First() (*model.LoginLog, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginLog), nil
	}
}

func (l loginLogDo) Take() (*model.LoginLog, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginLog), nil
	}
}

func (l loginLogDo) Last() (*model.LoginLog, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginLog), nil
	}
}

func (l loginLogDo) Find() ([]*model.LoginLog, error) {
	result, err := l.DO.Find()
	return result.([]*model.LoginLog), err
}

func (l loginLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoginLog, err error) {
	buf := make([]*model.LoginLog, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loginLogDo) FindInBatches(result *[]*model.LoginLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loginLogDo) Attrs(attrs ...field.AssignExpr) *loginLogDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loginLogDo) Assign(attrs ...field.AssignExpr) *loginLogDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loginLogDo) Joins(fields ...field.RelationField) *loginLogDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loginLogDo) Preload(fields ...field.RelationField) *loginLogDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loginLogDo) FirstOrInit() (*model.LoginLog, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginLog), nil
	}
}

func (l loginLogDo) FirstOrCreate() (*model.LoginLog, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginLog), nil
	}
}

func (l loginLogDo) FindByPage(offset int, limit int) (result []*model.LoginLog, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loginLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loginLogDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loginLogDo) Delete(models ...*model.LoginLog) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loginLogDo) withDO(do gen.Dao) *loginLogDo {
	l.DO = *do.(*gen.DO)
	return l
}
