// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newTaggable(db *gorm.DB, opts ...gen.DOOption) taggable {
	_taggable := taggable{}

	_taggable.taggableDo.UseDB(db, opts...)
	_taggable.taggableDo.UseModel(&model.Taggable{})

	tableName := _taggable.taggableDo.TableName()
	_taggable.ALL = field.NewAsterisk(tableName)
	_taggable.ID = field.NewString(tableName, "id")
	_taggable.TaggableType = field.NewString(tableName, "taggable_type")
	_taggable.TaggableID = field.NewString(tableName, "taggable_id")
	_taggable.TagID = field.NewString(tableName, "tag_id")
	_taggable.CreatedAt = field.NewTime(tableName, "created_at")

	_taggable.fillFieldMap()

	return _taggable
}

type taggable struct {
	taggableDo

	ALL          field.Asterisk
	ID           field.String
	TaggableType field.String
	TaggableID   field.String
	TagID        field.String
	CreatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t taggable) Table(newTableName string) *taggable {
	t.taggableDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taggable) As(alias string) *taggable {
	t.taggableDo.DO = *(t.taggableDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taggable) updateTableName(table string) *taggable {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TaggableType = field.NewString(table, "taggable_type")
	t.TaggableID = field.NewString(table, "taggable_id")
	t.TagID = field.NewString(table, "tag_id")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *taggable) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taggable) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 5)
	t.fieldMap["id"] = t.ID
	t.fieldMap["taggable_type"] = t.TaggableType
	t.fieldMap["taggable_id"] = t.TaggableID
	t.fieldMap["tag_id"] = t.TagID
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t taggable) clone(db *gorm.DB) taggable {
	t.taggableDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taggable) replaceDB(db *gorm.DB) taggable {
	t.taggableDo.ReplaceDB(db)
	return t
}

type taggableDo struct{ gen.DO }

func (t taggableDo) Debug() *taggableDo {
	return t.withDO(t.DO.Debug())
}

func (t taggableDo) WithContext(ctx context.Context) *taggableDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taggableDo) ReadDB() *taggableDo {
	return t.Clauses(dbresolver.Read)
}

func (t taggableDo) WriteDB() *taggableDo {
	return t.Clauses(dbresolver.Write)
}

func (t taggableDo) Session(config *gorm.Session) *taggableDo {
	return t.withDO(t.DO.Session(config))
}

func (t taggableDo) Clauses(conds ...clause.Expression) *taggableDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taggableDo) Returning(value interface{}, columns ...string) *taggableDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taggableDo) Not(conds ...gen.Condition) *taggableDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taggableDo) Or(conds ...gen.Condition) *taggableDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taggableDo) Select(conds ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taggableDo) Where(conds ...gen.Condition) *taggableDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taggableDo) Order(conds ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taggableDo) Distinct(cols ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taggableDo) Omit(cols ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taggableDo) Join(table schema.Tabler, on ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taggableDo) LeftJoin(table schema.Tabler, on ...field.Expr) *taggableDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taggableDo) RightJoin(table schema.Tabler, on ...field.Expr) *taggableDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taggableDo) Group(cols ...field.Expr) *taggableDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taggableDo) Having(conds ...gen.Condition) *taggableDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taggableDo) Limit(limit int) *taggableDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taggableDo) Offset(offset int) *taggableDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taggableDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *taggableDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taggableDo) Unscoped() *taggableDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taggableDo) Create(values ...*model.Taggable) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taggableDo) CreateInBatches(values []*model.Taggable, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taggableDo) Save(values ...*model.Taggable) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taggableDo) First() (*model.Taggable, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Taggable), nil
	}
}

func (t taggableDo) Take() (*model.Taggable, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Taggable), nil
	}
}

func (t taggableDo) Last() (*model.Taggable, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Taggable), nil
	}
}

func (t taggableDo) Find() ([]*model.Taggable, error) {
	result, err := t.DO.Find()
	return result.([]*model.Taggable), err
}

func (t taggableDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Taggable, err error) {
	buf := make([]*model.Taggable, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taggableDo) FindInBatches(result *[]*model.Taggable, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taggableDo) Attrs(attrs ...field.AssignExpr) *taggableDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taggableDo) Assign(attrs ...field.AssignExpr) *taggableDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taggableDo) Joins(fields ...field.RelationField) *taggableDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taggableDo) Preload(fields ...field.RelationField) *taggableDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taggableDo) FirstOrInit() (*model.Taggable, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Taggable), nil
	}
}

func (t taggableDo) FirstOrCreate() (*model.Taggable, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Taggable), nil
	}
}

func (t taggableDo) FindByPage(offset int, limit int) (result []*model.Taggable, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taggableDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taggableDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taggableDo) Delete(models ...*model.Taggable) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taggableDo) withDO(do gen.Dao) *taggableDo {
	t.DO = *do.(*gen.DO)
	return t
}
