// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newTenantMember(db *gorm.DB, opts ...gen.DOOption) tenantMember {
	_tenantMember := tenantMember{}

	_tenantMember.tenantMemberDo.UseDB(db, opts...)
	_tenantMember.tenantMemberDo.UseModel(&model.TenantMember{})

	tableName := _tenantMember.tenantMemberDo.TableName()
	_tenantMember.ALL = field.NewAsterisk(tableName)
	_tenantMember.ID = field.NewString(tableName, "id")
	_tenantMember.TenantID = field.NewString(tableName, "tenant_id")
	_tenantMember.UserID = field.NewString(tableName, "user_id")
	_tenantMember.Role = field.NewString(tableName, "role")
	_tenantMember.Status = field.NewString(tableName, "status")
	_tenantMember.InvitedBy = field.NewString(tableName, "invited_by")
	_tenantMember.JoinedAt = field.NewTime(tableName, "joined_at")
	_tenantMember.LeftAt = field.NewTime(tableName, "left_at")
	_tenantMember.CreatedAt = field.NewTime(tableName, "created_at")
	_tenantMember.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tenantMember.fillFieldMap()

	return _tenantMember
}

type tenantMember struct {
	tenantMemberDo

	ALL       field.Asterisk
	ID        field.String // 成员关系唯一标识
	TenantID  field.String // 关联的租户 ID
	UserID    field.String // 关联的用户 ID
	Role      field.String // 成员角色：member 普通成员，guest 访客，admin 管理员，owner 所有者
	Status    field.String // 成员状态：active 活跃，inactive 非活跃，removed 已移除
	InvitedBy field.String // 邀请人 ID
	JoinedAt  field.Time   // 加入时间
	LeftAt    field.Time   // 离开时间
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t tenantMember) Table(newTableName string) *tenantMember {
	t.tenantMemberDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenantMember) As(alias string) *tenantMember {
	t.tenantMemberDo.DO = *(t.tenantMemberDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenantMember) updateTableName(table string) *tenantMember {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TenantID = field.NewString(table, "tenant_id")
	t.UserID = field.NewString(table, "user_id")
	t.Role = field.NewString(table, "role")
	t.Status = field.NewString(table, "status")
	t.InvitedBy = field.NewString(table, "invited_by")
	t.JoinedAt = field.NewTime(table, "joined_at")
	t.LeftAt = field.NewTime(table, "left_at")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tenantMember) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenantMember) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["role"] = t.Role
	t.fieldMap["status"] = t.Status
	t.fieldMap["invited_by"] = t.InvitedBy
	t.fieldMap["joined_at"] = t.JoinedAt
	t.fieldMap["left_at"] = t.LeftAt
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tenantMember) clone(db *gorm.DB) tenantMember {
	t.tenantMemberDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenantMember) replaceDB(db *gorm.DB) tenantMember {
	t.tenantMemberDo.ReplaceDB(db)
	return t
}

type tenantMemberDo struct{ gen.DO }

func (t tenantMemberDo) Debug() *tenantMemberDo {
	return t.withDO(t.DO.Debug())
}

func (t tenantMemberDo) WithContext(ctx context.Context) *tenantMemberDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenantMemberDo) ReadDB() *tenantMemberDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenantMemberDo) WriteDB() *tenantMemberDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenantMemberDo) Session(config *gorm.Session) *tenantMemberDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenantMemberDo) Clauses(conds ...clause.Expression) *tenantMemberDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenantMemberDo) Returning(value interface{}, columns ...string) *tenantMemberDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenantMemberDo) Not(conds ...gen.Condition) *tenantMemberDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenantMemberDo) Or(conds ...gen.Condition) *tenantMemberDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenantMemberDo) Select(conds ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenantMemberDo) Where(conds ...gen.Condition) *tenantMemberDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenantMemberDo) Order(conds ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenantMemberDo) Distinct(cols ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenantMemberDo) Omit(cols ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenantMemberDo) Join(table schema.Tabler, on ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenantMemberDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenantMemberDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenantMemberDo) Group(cols ...field.Expr) *tenantMemberDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenantMemberDo) Having(conds ...gen.Condition) *tenantMemberDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenantMemberDo) Limit(limit int) *tenantMemberDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenantMemberDo) Offset(offset int) *tenantMemberDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenantMemberDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenantMemberDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenantMemberDo) Unscoped() *tenantMemberDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenantMemberDo) Create(values ...*model.TenantMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenantMemberDo) CreateInBatches(values []*model.TenantMember, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenantMemberDo) Save(values ...*model.TenantMember) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenantMemberDo) First() (*model.TenantMember, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Take() (*model.TenantMember, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Last() (*model.TenantMember, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) Find() ([]*model.TenantMember, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenantMember), err
}

func (t tenantMemberDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantMember, err error) {
	buf := make([]*model.TenantMember, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenantMemberDo) FindInBatches(result *[]*model.TenantMember, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenantMemberDo) Attrs(attrs ...field.AssignExpr) *tenantMemberDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenantMemberDo) Assign(attrs ...field.AssignExpr) *tenantMemberDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenantMemberDo) Joins(fields ...field.RelationField) *tenantMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenantMemberDo) Preload(fields ...field.RelationField) *tenantMemberDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenantMemberDo) FirstOrInit() (*model.TenantMember, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) FirstOrCreate() (*model.TenantMember, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantMember), nil
	}
}

func (t tenantMemberDo) FindByPage(offset int, limit int) (result []*model.TenantMember, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenantMemberDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenantMemberDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenantMemberDo) Delete(models ...*model.TenantMember) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenantMemberDo) withDO(do gen.Dao) *tenantMemberDo {
	t.DO = *do.(*gen.DO)
	return t
}
