// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-ddd-scaffold/internal/infrastructure/persistence/gorm/model"
)

func newTenantInvitation(db *gorm.DB, opts ...gen.DOOption) tenantInvitation {
	_tenantInvitation := tenantInvitation{}

	_tenantInvitation.tenantInvitationDo.UseDB(db, opts...)
	_tenantInvitation.tenantInvitationDo.UseModel(&model.TenantInvitation{})

	tableName := _tenantInvitation.tenantInvitationDo.TableName()
	_tenantInvitation.ALL = field.NewAsterisk(tableName)
	_tenantInvitation.ID = field.NewString(tableName, "id")
	_tenantInvitation.TenantID = field.NewString(tableName, "tenant_id")
	_tenantInvitation.Email = field.NewString(tableName, "email")
	_tenantInvitation.Role = field.NewString(tableName, "role")
	_tenantInvitation.Token = field.NewString(tableName, "token")
	_tenantInvitation.Status = field.NewString(tableName, "status")
	_tenantInvitation.ExpiresAt = field.NewTime(tableName, "expires_at")
	_tenantInvitation.CreatorID = field.NewString(tableName, "creator_id")
	_tenantInvitation.AcceptedBy = field.NewString(tableName, "accepted_by")
	_tenantInvitation.AcceptedAt = field.NewTime(tableName, "accepted_at")
	_tenantInvitation.RejectedAt = field.NewTime(tableName, "rejected_at")
	_tenantInvitation.CreatedAt = field.NewTime(tableName, "created_at")
	_tenantInvitation.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tenantInvitation.fillFieldMap()

	return _tenantInvitation
}

type tenantInvitation struct {
	tenantInvitationDo

	ALL        field.Asterisk
	ID         field.String // 邀请唯一标识
	TenantID   field.String // 关联的租户 ID
	Email      field.String // 被邀请人邮箱
	Role       field.String // 邀请的角色
	Token      field.String // 邀请令牌
	Status     field.String // 邀请状态：pending 待处理，accepted 已接受，rejected 已拒绝，expired 已过期
	ExpiresAt  field.Time   // 邀请过期时间
	CreatorID  field.String // 创建人 ID
	AcceptedBy field.String // 接受人 ID
	AcceptedAt field.Time   // 接受时间
	RejectedAt field.Time   // 拒绝时间
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (t tenantInvitation) Table(newTableName string) *tenantInvitation {
	t.tenantInvitationDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tenantInvitation) As(alias string) *tenantInvitation {
	t.tenantInvitationDo.DO = *(t.tenantInvitationDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tenantInvitation) updateTableName(table string) *tenantInvitation {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TenantID = field.NewString(table, "tenant_id")
	t.Email = field.NewString(table, "email")
	t.Role = field.NewString(table, "role")
	t.Token = field.NewString(table, "token")
	t.Status = field.NewString(table, "status")
	t.ExpiresAt = field.NewTime(table, "expires_at")
	t.CreatorID = field.NewString(table, "creator_id")
	t.AcceptedBy = field.NewString(table, "accepted_by")
	t.AcceptedAt = field.NewTime(table, "accepted_at")
	t.RejectedAt = field.NewTime(table, "rejected_at")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tenantInvitation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tenantInvitation) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["email"] = t.Email
	t.fieldMap["role"] = t.Role
	t.fieldMap["token"] = t.Token
	t.fieldMap["status"] = t.Status
	t.fieldMap["expires_at"] = t.ExpiresAt
	t.fieldMap["creator_id"] = t.CreatorID
	t.fieldMap["accepted_by"] = t.AcceptedBy
	t.fieldMap["accepted_at"] = t.AcceptedAt
	t.fieldMap["rejected_at"] = t.RejectedAt
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tenantInvitation) clone(db *gorm.DB) tenantInvitation {
	t.tenantInvitationDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tenantInvitation) replaceDB(db *gorm.DB) tenantInvitation {
	t.tenantInvitationDo.ReplaceDB(db)
	return t
}

type tenantInvitationDo struct{ gen.DO }

func (t tenantInvitationDo) Debug() *tenantInvitationDo {
	return t.withDO(t.DO.Debug())
}

func (t tenantInvitationDo) WithContext(ctx context.Context) *tenantInvitationDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tenantInvitationDo) ReadDB() *tenantInvitationDo {
	return t.Clauses(dbresolver.Read)
}

func (t tenantInvitationDo) WriteDB() *tenantInvitationDo {
	return t.Clauses(dbresolver.Write)
}

func (t tenantInvitationDo) Session(config *gorm.Session) *tenantInvitationDo {
	return t.withDO(t.DO.Session(config))
}

func (t tenantInvitationDo) Clauses(conds ...clause.Expression) *tenantInvitationDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tenantInvitationDo) Returning(value interface{}, columns ...string) *tenantInvitationDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tenantInvitationDo) Not(conds ...gen.Condition) *tenantInvitationDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tenantInvitationDo) Or(conds ...gen.Condition) *tenantInvitationDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tenantInvitationDo) Select(conds ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tenantInvitationDo) Where(conds ...gen.Condition) *tenantInvitationDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tenantInvitationDo) Order(conds ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tenantInvitationDo) Distinct(cols ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tenantInvitationDo) Omit(cols ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tenantInvitationDo) Join(table schema.Tabler, on ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tenantInvitationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tenantInvitationDo) RightJoin(table schema.Tabler, on ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tenantInvitationDo) Group(cols ...field.Expr) *tenantInvitationDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tenantInvitationDo) Having(conds ...gen.Condition) *tenantInvitationDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tenantInvitationDo) Limit(limit int) *tenantInvitationDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tenantInvitationDo) Offset(offset int) *tenantInvitationDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tenantInvitationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *tenantInvitationDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tenantInvitationDo) Unscoped() *tenantInvitationDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tenantInvitationDo) Create(values ...*model.TenantInvitation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tenantInvitationDo) CreateInBatches(values []*model.TenantInvitation, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tenantInvitationDo) Save(values ...*model.TenantInvitation) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tenantInvitationDo) First() (*model.TenantInvitation, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantInvitation), nil
	}
}

func (t tenantInvitationDo) Take() (*model.TenantInvitation, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantInvitation), nil
	}
}

func (t tenantInvitationDo) Last() (*model.TenantInvitation, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantInvitation), nil
	}
}

func (t tenantInvitationDo) Find() ([]*model.TenantInvitation, error) {
	result, err := t.DO.Find()
	return result.([]*model.TenantInvitation), err
}

func (t tenantInvitationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TenantInvitation, err error) {
	buf := make([]*model.TenantInvitation, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tenantInvitationDo) FindInBatches(result *[]*model.TenantInvitation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tenantInvitationDo) Attrs(attrs ...field.AssignExpr) *tenantInvitationDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tenantInvitationDo) Assign(attrs ...field.AssignExpr) *tenantInvitationDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tenantInvitationDo) Joins(fields ...field.RelationField) *tenantInvitationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tenantInvitationDo) Preload(fields ...field.RelationField) *tenantInvitationDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tenantInvitationDo) FirstOrInit() (*model.TenantInvitation, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantInvitation), nil
	}
}

func (t tenantInvitationDo) FirstOrCreate() (*model.TenantInvitation, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TenantInvitation), nil
	}
}

func (t tenantInvitationDo) FindByPage(offset int, limit int) (result []*model.TenantInvitation, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tenantInvitationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tenantInvitationDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tenantInvitationDo) Delete(models ...*model.TenantInvitation) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tenantInvitationDo) withDO(do gen.Dao) *tenantInvitationDo {
	t.DO = *do.(*gen.DO)
	return t
}
