#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
API Generator - RESTful API 端点生成器
根据 DDD 聚合根自动生成完整的 API 端点、Handler、DTO 和 Swagger 文档
"""

import os
import sys
import argparse
import json
from pathlib import Path
from datetime import datetime


def parse_args():
    """解析命令行参数"""
    parser = argparse.ArgumentParser(
        description='RESTful API 端点生成器',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  # 生成单个聚合的 API
  %(prog)s --aggregate UserAggregate
  
  # 批量生成多个聚合
  %(prog)s --aggregates User,Order,Product
  
  # 启用 JWT 认证和验证
  %(prog)s --aggregate User --with-validation --auth jwt
  
  # 指定输出目录和前缀
  %(prog)s --aggregate Product --output ./custom/api --prefix /api/v1
        """
    )
    
    parser.add_argument(
        '--aggregate',
        type=str,
        help='聚合根名称 (如：UserAggregate)'
    )
    
    parser.add_argument(
        '--aggregates',
        type=str,
        help='多个聚合根列表，逗号分隔'
    )
    
    parser.add_argument(
        '--output',
        type=str,
        default='./generated',
        help='输出目录 (默认：./generated)'
    )
    
    parser.add_argument(
        '--prefix',
        type=str,
        default='/api/v1',
        help='API 路径前缀 (默认：/api/v1)'
    )
    
    parser.add_argument(
        '--with-validation',
        action='store_true',
        help='包含参数验证逻辑'
    )
    
    parser.add_argument(
        '--with-tests',
        action='store_true',
        help='包含测试文件'
    )
    
    parser.add_argument(
        '--auth',
        type=str,
        choices=['none', 'jwt', 'casbin'],
        default='jwt',
        help='认证方式 (默认：jwt)'
    )
    
    parser.add_argument(
        '--config',
        type=str,
        help='自定义配置文件路径'
    )
    
    return parser.parse_args()


def validate_aggregate_name(name):
    """验证聚合根名称"""
    if not name.endswith('Aggregate'):
        print(f"⚠️  警告：聚合根名称通常以 'Aggregate' 结尾 (当前：{name})")
    return True


def extract_entity_name(aggregate_name):
    """从聚合根名称提取实体名称"""
    # UserAggregate -> user
    # OrderAggregate -> order
    return aggregate_name.replace('Aggregate', '').lower()


def generate_handler_code(aggregate_name, entity_name, config):
    """生成 Handler 代码"""
    handler_class = f"{entity_name.title()}Handler"
    
    code = f'''// Code generated by api-generator. DO NOT EDIT.
// source: {aggregate_name}

package http

import (
\t"net/http"
\t"strconv"

\t"github.com/gin-gonic/gin"
\t"your-project/internal/application/{entity_name}/dto"
\t"your-project/internal/application/{entity_name}/service"
\t"your-project/pkg/response"
)

// {handler_class} HTTP Handler
type {handler_class} struct {{
\tservice *service.{entity_name.title()}AppService
}}

// New{entity_name.title()}Handler 构造函数
func New{entity_name.title()}Handler(service *service.{entity_name.title()}AppService) *{handler_class} {{
\treturn &{handler_class}{{
\t\tservice: service,
\t}}
}}
'''
    
    # 添加 Create 方法
    if config.get('with_validation'):
        code += f'''
// Create{entity_name.title()} 创建
// @Summary Create {entity_name.title()}
// @Tags {entity_name.title()}Management
// @Accept json
// @Produce json
'''
    
    if config.get('auth') == 'jwt':
        code += '''// @Security BearerAuth
'''
    
    code += f'''// @Param {entity_name} body dto.Create{entity_name.title()}Request true "{entity_name.title()} information"
// @Success 201 {{object}} response.Response{{data=dto.{entity_name.title()}Response}}
// @Failure 400 {{object}} response.ErrorResponse
// @Router {config['prefix']}/{entity_name}s [post]
func (h *{handler_class}) Create{entity_name.title()}(c *gin.Context) {{
\tvar req dto.Create{entity_name.title()}Request
\tif err := c.ShouldBindJSON(&req); err != nil {{
\t\tc.JSON(http.StatusBadRequest, response.Error(err))
\t\treturn
\t}}
'''
    
    if config.get('auth') == 'jwt':
        code += '''
\t// JWT authentication - get current user ID
\tuserID := c.GetString("user_id")
\t_ = userID // TODO: Use userID in service call
'''
    
    code += f'''
\t// Call application service
\tresult, err := h.service.Create{entity_name.title()}(c.Request.Context(), req)
\tif err != nil {{
\t\tc.JSON(response.HTTPStatus(err), response.Error(err))
\t\treturn
\t}}
\t
\tc.JSON(http.StatusCreated, response.Success(result))
}}
'''
    
    # 添加 Get 方法
    code += f'''
// Get{entity_name.title()} 获取详情
// @Summary Get {entity_name.title()} Details
// @Tags {entity_name.title()}Management
// @Accept json
// @Produce json
'''
    
    if config.get('auth') == 'jwt':
        code += '''// @Security BearerAuth
'''
    
    code += f'''// @Param id path string true "{entity_name.title()} ID"
// @Success 200 {{object}} response.Response{{data=dto.{entity_name.title()}Response}}
// @Failure 404 {{object}} response.ErrorResponse
// @Router {config['prefix']}/{entity_name}s/{{id}} [get]
func (h *{handler_class}) Get{entity_name.title()}(c *gin.Context) {{
\tid := c.Param("id")
\t
\tresult, err := h.service.Get{entity_name.title()}ByID(c.Request.Context(), id)
\tif err != nil {{
\t\tc.JSON(response.HTTPStatus(err), response.Error(err))
\t\treturn
\t}}
\t
\tc.JSON(http.StatusOK, response.Success(result))
}}
'''
    
    # 添加 List 方法
    code += f'''
// List{entity_name.title()}s 获取列表
// @Summary List {entity_name.title()}s
// @Tags {entity_name.title()}Management
// @Accept json
// @Produce json
'''
    
    if config.get('auth') == 'jwt':
        code += '''// @Security BearerAuth
'''
    
    code += f'''// @Param page query int false "Page number" default(1)
// @Param pageSize query int false "Items per page" default(20)
// @Success 200 {{object}} response.Response{{data=dto.List{entity_name.title()}sResponse}}
// @Router {config['prefix']}/{entity_name}s [get]
func (h *{handler_class}) List{entity_name.title()}s(c *gin.Context) {{
\tpage, _ := strconv.Atoi(c.DefaultQuery("page", "1"))
\tpageSize, _ := strconv.Atoi(c.DefaultQuery("pageSize", "20"))
\t
\tresult, err := h.service.List{entity_name.title()}s(c.Request.Context(), page, pageSize)
\tif err != nil {{
\t\tc.JSON(response.HTTPStatus(err), response.Error(err))
\t\treturn
\t}}
\t
\tc.JSON(http.StatusOK, response.Success(result))
}}
'''
    
    # 添加 Update 方法
    code += f'''
// Update{entity_name.title()} 更新
// @Summary Update {entity_name.title()}
// @Tags {entity_name.title()}Management
// @Accept json
// @Produce json
'''
    
    if config.get('auth') == 'jwt':
        code += '''// @Security BearerAuth
'''
    
    code += f'''// @Param id path string true "{entity_name.title()} ID"
// @Param {entity_name} body dto.Update{entity_name.title()}Request true "{entity_name.title()} information"
// @Success 200 {{object}} response.Response{{data=dto.{entity_name.title()}Response}}
// @Router {config['prefix']}/{entity_name}s/{{id}} [put]
func (h *{handler_class}) Update{entity_name.title()}(c *gin.Context) {{
\tid := c.Param("id")
\t
\tvar req dto.Update{entity_name.title()}Request
\tif err := c.ShouldBindJSON(&req); err != nil {{
\t\tc.JSON(http.StatusBadRequest, response.Error(err))
\t\treturn
\t}}
\t
\tresult, err := h.service.Update{entity_name.title()}(c.Request.Context(), id, req)
\tif err != nil {{
\t\tc.JSON(response.HTTPStatus(err), response.Error(err))
\t\treturn
\t}}
\t
\tc.JSON(http.StatusOK, response.Success(result))
}}
'''
    
    # 添加 Delete 方法
    code += f'''
// Delete{entity_name.title()} 删除
// @Summary Delete {entity_name.title()}
// @Tags {entity_name.title()}Management
// @Accept json
// @Produce json
'''
    
    if config.get('auth') == 'jwt':
        code += '''// @Security BearerAuth
'''
    
    code += f'''// @Param id path string true "{entity_name.title()} ID"
// @Success 204
// @Router {config['prefix']}/{entity_name}s/{{id}} [delete]
func (h *{handler_class}) Delete{entity_name.title()}(c *gin.Context) {{
\tid := c.Param("id")
\t
\terr := h.service.Delete{entity_name.title()}(c.Request.Context(), id)
\tif err != nil {{
\t\tc.JSON(response.HTTPStatus(err), response.Error(err))
\t\treturn
\t}}
\t
\tc.Status(http.StatusNoContent)
}}
'''
    
    return code


def generate_dto_code(aggregate_name, entity_name, config):
    """生成 DTO 代码"""
    entity_class = entity_name.title()
    
    code = f'''// Code generated by api-generator. DO NOT EDIT.
// source: {aggregate_name}

package dto

import (
\t"time"
)

// Create{entity_class}Request 创建请求
type Create{entity_class}Request struct {{
\tName  string `json:"name" binding:"required,min=2,max=50"`
\tEmail string `json:"email" binding:"required,email"`
\t// Add more fields as needed
}}

// Update{entity_class}Request 更新请求
type Update{entity_class}Request struct {{
\tName  string `json:"name" binding:"omitempty,min=2,max=50"`
\tEmail string `json:"email" binding:"omitempty,email"`
\t// Add more fields as needed
}}

// {entity_class}Response {entity_class.lower()} 响应
type {entity_class}Response struct {{
\tID        string    `json:"id"`
\tName      string    `json:"name"`
\tEmail     string    `json:"email"`
\tCreatedAt time.Time `json:"created_at"`
\tUpdatedAt time.Time `json:"updated_at"`
\t// Add more fields as needed
}}

// List{entity_class}esResponse {entity_class.lower()} 列表响应
type List{entity_class}esResponse struct {{
\tItems      []{entity_class}Response `json:"items"`
\tTotal      int64                    `json:"total"`
\tPage       int                      `json:"page"`
\tPageSize   int                      `json:"page_size"`
\tTotalPages int                      `json:"total_pages"`
}}
'''
    
    return code


def generate_router_code(entity_name, config):
    """生成 Router 代码"""
    handler_class = f"{entity_name.title()}Handler"
    
    code = f'''// Code generated by api-generator. DO NOT EDIT.
// source: {entity_name.title()}Aggregate

package http

import (
\t"github.com/gin-gonic/gin"
)

// Register{entity_name.title()}Routes 注册{entity_name.title()}路由
func Register{entity_name.title()}Routes(r *gin.RouterGroup, handler *{handler_class}) {{
\tgroup := r.Group("/{entity_name}s")
\t{{
\t\t// Public routes (no authentication required)
\t\tgroup.POST("", handler.Create{entity_name.title()})
\t\tgroup.GET("", handler.List{entity_name.title()}s)
\t\tgroup.GET("/:id", handler.Get{entity_name.title()})
\t\tgroup.PUT("/:id", handler.Update{entity_name.title()})
\t\tgroup.DELETE("/:id", handler.Delete{entity_name.title()})
\t}}
}}
'''
    
    return code


def main():
    """主函数"""
    args = parse_args()
    
    # 确定要处理的聚合列表
    aggregates = []
    if args.aggregate:
        aggregates = [args.aggregate]
    elif args.aggregates:
        aggregates = [a.strip() for a in args.aggregates.split(',')]
    else:
        print("❌ 错误：必须指定聚合根 (--aggregate 或 --aggregates)")
        sys.exit(1)
    
    # 配置
    config = {
        'output': args.output,
        'prefix': args.prefix,
        'with_validation': args.with_validation,
        'with_tests': args.with_tests,
        'auth': args.auth,
    }
    
    print(f"\n🚀 开始生成 API 端点")
    print(f"   聚合：{', '.join(aggregates)}")
    print(f"   输出：{config['output']}")
    print(f"   前缀：{config['prefix']}")
    print(f"   认证：{config['auth']}")
    print(f"   验证：{'是' if config['with_validation'] else '否'}\n")
    
    base_path = Path(config['output'])
    
    for aggregate in aggregates:
        try:
            # 验证聚合根名称
            validate_aggregate_name(aggregate)
            
            # 提取实体名称
            entity_name = extract_entity_name(aggregate)
            
            # 创建目录
            handler_dir = base_path / 'internal' / 'interfaces' / 'http' / entity_name
            handler_dir.mkdir(parents=True, exist_ok=True)
            
            # 生成 Handler
            handler_code = generate_handler_code(aggregate, entity_name, config)
            handler_file = handler_dir / f"{entity_name}_handler.go"
            with open(handler_file, 'w', encoding='utf-8') as f:
                f.write(handler_code)
            print(f"✓ 生成 Handler: {handler_file}")
            
            # 生成 DTO
            dto_dir = base_path / 'internal' / 'application' / entity_name / 'dto'
            dto_dir.mkdir(parents=True, exist_ok=True)
            dto_code = generate_dto_code(aggregate, entity_name, config)
            dto_file = dto_dir / f"{entity_name}_dto.go"
            with open(dto_file, 'w', encoding='utf-8') as f:
                f.write(dto_code)
            print(f"✓ 生成 DTO: {dto_file}")
            
            # 生成 Router
            router_code = generate_router_code(entity_name, config)
            router_file = handler_dir / f"{entity_name}_router.go"
            with open(router_file, 'w', encoding='utf-8') as f:
                f.write(router_code)
            print(f"✓ 生成 Router: {router_file}")
            
            print()
            
        except Exception as e:
            print(f"❌ 生成 {aggregate} 失败：{e}")
            import traceback
            traceback.print_exc()
            continue
    
    print("\n✅ API 端点生成完成!\n")
    print("下一步:")
    print(f"  1. 检查生成的代码：cd {base_path}")
    print(f"  2. 根据需要修改业务逻辑")
    print(f"  3. 运行 swag 生成 API 文档：swag init")
    print(f"  4. 启动应用测试：make run\n")


if __name__ == '__main__':
    main()
