// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKgAcademicConcept = "kg_academic_concepts"

// KgAcademicConcept mapped from table <kg_academic_concepts>
type KgAcademicConcept struct {
	ID        *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:学术概念唯一标识符" json:"id"`                                         // 学术概念唯一标识符
	Name      string     `gorm:"column:name;type:character varying(255);not null;comment:概念名称 (e.g., "方程")" json:"name"`                                       // 概念名称 (e.g., "方程")
	Level     *string    `gorm:"column:level;type:character varying(100);comment:学术层级 (e.g., "基础", "高级")" json:"level"`                                        // 学术层级 (e.g., "基础", "高级")
	Field     *string    `gorm:"column:field;type:character varying(255);comment:所属学术领域 (e.g., "代数")" json:"field"`                                            // 所属学术领域 (e.g., "代数")
	NodeID    *string    `gorm:"column:node_id;type:uuid;index:idx_kg_academic_concepts_node_id,priority:1;comment:关联的知识图谱节点ID，用于将学术概念与知识节点关联" json:"node_id"` // 关联的知识图谱节点ID，用于将学术概念与知识节点关联
	Metadata  *string    `gorm:"column:metadata;type:jsonb;default:{};comment:额外元数据" json:"metadata"`                                                          // 额外元数据
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now();comment:创建时间" json:"created_at"`                                 // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now();comment:更新时间" json:"updated_at"`                                 // 更新时间
}

// TableName KgAcademicConcept's table name
func (*KgAcademicConcept) TableName() string {
	return TableNameKgAcademicConcept
}
