// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKgNode = "kg_nodes"

// KgNode mapped from table <kg_nodes>
type KgNode struct {
	ID                        *string              `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TrunkID                   *string              `gorm:"column:trunk_id;type:uuid;index:idx_kg_nodes_trunk_id,priority:1" json:"trunk_id"`
	Type                      string               `gorm:"column:type;type:character varying(10);not null;index:idx_kg_nodes_type,priority:1" json:"type"`
	CompetencyLevelID         *string              `gorm:"column:competency_level_id;type:uuid;index:idx_kg_nodes_competency_level_id,priority:1" json:"competency_level_id"`
	NameChildKey              *string              `gorm:"column:name_child_key;type:character varying(500)" json:"name_child_key"`
	NameParentKey             *string              `gorm:"column:name_parent_key;type:character varying(500)" json:"name_parent_key"`
	DescriptionKey            *string              `gorm:"column:description_key;type:text" json:"description_key"`
	AcademicConceptID         *string              `gorm:"column:academic_concept_id;type:uuid;index:idx_kg_nodes_academic_concept_id,priority:1" json:"academic_concept_id"`
	Resources                 *string              `gorm:"column:resources;type:jsonb;default:{}" json:"resources"`
	IsActive                  *bool                `gorm:"column:is_active;type:boolean;index:idx_kg_nodes_is_active,priority:1;default:true" json:"is_active"`
	Metadata                  *string              `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt                 *time.Time           `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt                 *time.Time           `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
	Trunk                     KgTrunk              `gorm:"foreignKey:TrunkID" json:"trunk"`
	NodeRelationshipsAsSource []KgNodeRelationship `gorm:"foreignKey:FromNodeID" json:"node_relationships_as_source"`
	NodeRelationshipsAsTarget []KgNodeRelationship `gorm:"foreignKey:ToNodeID" json:"node_relationships_as_target"`
}

// TableName KgNode's table name
func (*KgNode) TableName() string {
	return TableNameKgNode
}
