// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKgTrunk = "kg_trunks"

// KgTrunk mapped from table <kg_trunks>
type KgTrunk struct {
	ID             *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	DomainID       *string    `gorm:"column:domain_id;type:uuid" json:"domain_id"`
	NameKey        *string    `gorm:"column:name_key;type:character varying(500)" json:"name_key"`
	DescriptionKey *string    `gorm:"column:description_key;type:text" json:"description_key"`
	AcademicSource *string    `gorm:"column:academic_source;type:text" json:"academic_source"`
	IsActive       *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	Metadata       *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
	Domain         KgDomain   `gorm:"foreignKey:DomainID" json:"domain"`
	Nodes          []KgNode   `gorm:"foreignKey:TrunkID" json:"nodes"`
}

// TableName KgTrunk's table name
func (*KgTrunk) TableName() string {
	return TableNameKgTrunk
}
