// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLearnSideQuest = "learn_side_quests"

// LearnSideQuest mapped from table <learn_side_quests>
type LearnSideQuest struct {
	ID                   *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	NameKey              *string    `gorm:"column:name_key;type:character varying(500)" json:"name_key"`
	DescriptionKey       *string    `gorm:"column:description_key;type:text" json:"description_key"`
	TargetNodeID         *string    `gorm:"column:target_node_id;type:uuid" json:"target_node_id"`
	Category             *string    `gorm:"column:category;type:character varying(100)" json:"category"`
	DifficultyLevel      *string    `gorm:"column:difficulty_level;type:character varying(50)" json:"difficulty_level"`
	Weight               *float64   `gorm:"column:weight;type:numeric(5,2);default:1.00" json:"weight"`
	TriggerConditionJSON *string    `gorm:"column:trigger_condition_json;type:jsonb;default:{}" json:"trigger_condition_json"`
	Content              *string    `gorm:"column:content;type:jsonb;default:{}" json:"content"`
	Reward               *string    `gorm:"column:reward;type:jsonb;default:{}" json:"reward"`
	IsActive             *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	Metadata             *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt            *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt            *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
	TargetNode           KgNode     `gorm:"foreignKey:TargetNodeID" json:"target_node"`
}

// TableName LearnSideQuest's table name
func (*LearnSideQuest) TableName() string {
	return TableNameLearnSideQuest
}
