// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLearnAssessmentItem = "learn_assessment_items"

// LearnAssessmentItem mapped from table <learn_assessment_items>
type LearnAssessmentItem struct {
	ID              *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	QuestionTextKey *string    `gorm:"column:question_text_key;type:text" json:"question_text_key"`
	CorrectAnswer   *string    `gorm:"column:correct_answer;type:text" json:"correct_answer"`
	DifficultyLevel *string    `gorm:"column:difficulty_level;type:character varying(50)" json:"difficulty_level"`
	IsActive        *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	Metadata        *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName LearnAssessmentItem's table name
func (*LearnAssessmentItem) TableName() string {
	return TableNameLearnAssessmentItem
}
