// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLearnStudentProgress = "learn_student_progress"

// LearnStudentProgress mapped from table <learn_student_progress>
type LearnStudentProgress struct {
	ID               *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	StudentID        string     `gorm:"column:student_id;type:character varying(255);not null;index:idx_learn_student_progress_student_id,priority:1" json:"student_id"`
	NodeID           *string    `gorm:"column:node_id;type:uuid;index:idx_learn_student_progress_node_id,priority:1" json:"node_id"`
	MasteryScore     *float64   `gorm:"column:mastery_score;type:numeric(5,4);default:0.0000" json:"mastery_score"`
	LastInteractedAt *time.Time `gorm:"column:last_interacted_at;type:timestamp with time zone" json:"last_interacted_at"`
	AttemptsCount    *int32     `gorm:"column:attempts_count;type:integer" json:"attempts_count"`
	Metadata         *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
	Node             KgNode     `gorm:"foreignKey:NodeID" json:"node"`
}

// TableName LearnStudentProgress's table name
func (*LearnStudentProgress) TableName() string {
	return TableNameLearnStudentProgress
}
