// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaggable = "taggables"

// Taggable mapped from table <taggables>
type Taggable struct {
	ID           *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	TaggableType string     `gorm:"column:taggable_type;type:character varying(100);not null;index:idx_taggables_taggable_type_id,priority:1" json:"taggable_type"`
	TaggableID   string     `gorm:"column:taggable_id;type:uuid;not null;index:idx_taggables_taggable_type_id,priority:2" json:"taggable_id"`
	TagID        *string    `gorm:"column:tag_id;type:uuid;index:idx_taggables_tag_id,priority:1" json:"tag_id"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	Tag          Tag        `gorm:"foreignKey:TagID" json:"tag"`
}

// TableName Taggable's table name
func (*Taggable) TableName() string {
	return TableNameTaggable
}
