// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID             *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	NameKey        *string    `gorm:"column:name_key;type:character varying(500)" json:"name_key"`
	DescriptionKey *string    `gorm:"column:description_key;type:text" json:"description_key"`
	Category       *string    `gorm:"column:category;type:character varying(100)" json:"category"`
	IsActive       *bool      `gorm:"column:is_active;type:boolean;default:true" json:"is_active"`
	Metadata       *string    `gorm:"column:metadata;type:jsonb;default:{}" json:"metadata"`
	CreatedAt      *time.Time `gorm:"column:created_at;type:timestamp with time zone;default:now()" json:"created_at"`
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:timestamp with time zone;default:now()" json:"updated_at"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
