// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenant = "tenants"

// Tenant mapped from table <tenants>
type Tenant struct {
	ID          *string            `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:租户唯一标识" json:"id"`                                                                                 // 租户唯一标识
	Name        string             `gorm:"column:name;type:character varying(100);not null;comment:租户名称" json:"name"`                                                                                         // 租户名称
	Description *string            `gorm:"column:description;type:character varying(500);comment:租户描述" json:"description"`                                                                                    // 租户描述
	MaxMembers  *int32             `gorm:"column:max_members;type:integer;not null;default:10;comment:最大成员数限制" json:"max_members"`                                                                            // 最大成员数限制
	ExpiredAt   time.Time          `gorm:"column:expired_at;type:timestamp with time zone;not null;index:idx_tenants_expired_at,priority:1;comment:租户过期时间" json:"expired_at"`                                 // 租户过期时间
	Status      *string            `gorm:"column:status;type:character varying(20);not null;index:idx_tenants_status,priority:1;default:active;comment:租户状态：active 活跃，expired 过期，suspended 暂停" json:"status"` // 租户状态：active 活跃，expired 过期，suspended 暂停
	CreatedAt   *time.Time         `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                 // 创建时间
	UpdatedAt   *time.Time         `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                 // 更新时间
	Members     []TenantMember     `gorm:"foreignKey:TenantID" json:"members"`
	Invitations []TenantInvitation `gorm:"foreignKey:TenantID" json:"invitations"`
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}
