// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTenantMember = "tenant_members"

// TenantMember mapped from table <tenant_members>
type TenantMember struct {
	ID        *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:成员关系唯一标识" json:"id"`                                                                                       // 成员关系唯一标识
	TenantID  string     `gorm:"column:tenant_id;type:uuid;not null;index:idx_tenant_members_tenant_id,priority:1;comment:关联的租户 ID" json:"tenant_id"`                                                       // 关联的租户 ID
	UserID    string     `gorm:"column:user_id;type:uuid;not null;index:idx_tenant_members_user_id,priority:1;comment:关联的用户 ID" json:"user_id"`                                                             // 关联的用户 ID
	Role      string     `gorm:"column:role;type:character varying(20);not null;index:idx_tenant_members_role,priority:1;comment:成员角色：member 普通成员，guest 访客，admin 管理员，owner 所有者" json:"role"`                // 成员角色：member 普通成员，guest 访客，admin 管理员，owner 所有者
	Status    *string    `gorm:"column:status;type:character varying(20);not null;index:idx_tenant_members_status,priority:1;default:active;comment:成员状态：active 活跃，inactive 非活跃，removed 已移除" json:"status"` // 成员状态：active 活跃，inactive 非活跃，removed 已移除
	InvitedBy *string    `gorm:"column:invited_by;type:uuid;comment:邀请人 ID" json:"invited_by"`                                                                                                              // 邀请人 ID
	JoinedAt  *time.Time `gorm:"column:joined_at;type:timestamp with time zone;not null;default:now();comment:加入时间" json:"joined_at"`                                                                       // 加入时间
	LeftAt    *time.Time `gorm:"column:left_at;type:timestamp with time zone;comment:离开时间" json:"left_at"`                                                                                                  // 离开时间
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now();comment:创建时间" json:"created_at"`                                                                     // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now();comment:更新时间" json:"updated_at"`                                                                     // 更新时间
	Tenant    Tenant     `gorm:"foreignKey:TenantID" json:"tenant"`
	User      User       `gorm:"foreignKey:UserID" json:"user"`
	Inviter   User       `gorm:"foreignKey:InvitedBy" json:"inviter"`
}

// TableName TenantMember's table name
func (*TenantMember) TableName() string {
	return TableNameTenantMember
}
